/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Transport;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;
import panchayatoperator.PanchayatData;
import vegetabletrading.Mail;
import vegetabletrading.ParabitDB;

/**
 *
 * @author HARSHIT
 */
public class AddVehicle extends javax.swing.JDialog {
    ParabitDB db1;
    PBThread pb;
    String pathimg1, pathimg2, pathimg3, pathimg4,toid,pcode,poid;
    /**
     * Creates new form AddVehicle
     */
    public AddVehicle(java.awt.Frame parent, boolean modal,String a,String b) {
        super(parent, modal);
        initComponents();
        toid = a;
        poid = b;
        transid.setText("Transport Owner Id : "+toid);
        getData();
    }
    
    class PBThread extends Thread
    {
        JProgressBar pbar;
        
        PBThread(JProgressBar pbar)
        {
            pbar = tovehpbar;
        }
        
        public void run()
        {
            int min = 0;
            int max = 50;
            
            tovehpbar.setMaximum(min);
            tovehpbar.setMaximum(max);
            tovehpbar.setValue(0);
            
            for(int i = min; i<max; i++)
            {
                tovehpbar.setValue(i);
                try {
                    sleep(30);
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
    }
    private void getData(){
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select PostingID from employee where empid = "+poid);
            db1.rs.next();
            pcode = db1.rs.getString(1);                        
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tovehcap = new javax.swing.JTextField();
        tovehno = new javax.swing.JTextField();
        tovehmodel = new javax.swing.JTextField();
        tovehtype = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tovehregno = new javax.swing.JTextField();
        tovehinsno = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        tovehpbar = new javax.swing.JProgressBar();
        tovehimg1 = new javax.swing.JButton();
        tovehimg2 = new javax.swing.JButton();
        tovehimg3 = new javax.swing.JButton();
        tovehimg4 = new javax.swing.JButton();
        tovehsub = new javax.swing.JButton();
        transid = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        totable = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        tovehrexdate = new com.toedter.calendar.JDateChooser();
        tovehiexdate = new com.toedter.calendar.JDateChooser();
        tovehfuel = new javax.swing.JComboBox<>();
        tovehnext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Vehicle Type");

        jLabel12.setText("Vehicle No.");

        jLabel22.setText("Vehicle Capacity");

        jLabel27.setText("Fuel Type");

        tovehno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehnoActionPerformed(evt);
            }
        });

        tovehtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Vehicle Type", "Truck", "Mini Truck", "Pickup", "Loading Auto", "Tractor with Trolly" }));

        jLabel28.setText("Vehicle Reg No.");

        jLabel29.setText("Vehicle Reg Expire Date");

        jLabel30.setText("Vehicle Insurance No.");

        jLabel31.setText("Vehicle Insurance Expire Date");

        tovehregno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehregnoActionPerformed(evt);
            }
        });

        jLabel32.setText("Vehicle Image :");

        tovehimg1.setText("Upload");
        tovehimg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehimg1ActionPerformed(evt);
            }
        });

        tovehimg2.setText("Upload");
        tovehimg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehimg2ActionPerformed(evt);
            }
        });

        tovehimg3.setText("Upload");
        tovehimg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehimg3ActionPerformed(evt);
            }
        });

        tovehimg4.setText("Upload");
        tovehimg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehimg4ActionPerformed(evt);
            }
        });

        tovehsub.setText("Submit / Register");
        tovehsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehsubActionPerformed(evt);
            }
        });

        transid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        totable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S No.", "Vehicle Type", "Vehicle No.", "Vehicle Model ", "Fuel Type", "Reg No and Exp Date", "Ins No and Exp Date", "Capacity", "Vehicle Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(totable);

        jLabel33.setText("Vehicle Model");

        tovehrexdate.setFocusTraversalPolicyProvider(true);

        tovehfuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Fuel Type", "Petrol", "Desiel", "CNG" }));

        tovehnext.setText("Next");
        tovehnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehnextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tovehtype, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tovehmodel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tovehcap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(tovehno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tovehfuel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tovehregno, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(tovehinsno))
                                    .addComponent(tovehpbar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tovehrexdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tovehiexdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(tovehimg1)
                                        .addGap(50, 50, 50)
                                        .addComponent(tovehimg2)
                                        .addGap(50, 50, 50)
                                        .addComponent(tovehimg3)
                                        .addGap(50, 50, 50)
                                        .addComponent(tovehimg4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tovehnext)))))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(transid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tovehsub)
                .addGap(101, 101, 101))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(transid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel27)
                                    .addComponent(tovehno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tovehtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tovehfuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(tovehcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33)
                                    .addComponent(tovehmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(tovehregno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tovehrexdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(tovehinsno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tovehiexdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tovehimg1)
                        .addComponent(tovehimg2)
                        .addComponent(tovehimg3)
                        .addComponent(tovehimg4)
                        .addComponent(tovehnext))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tovehpbar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tovehsub)
                .addGap(261, 261, 261))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1017, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tovehnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tovehnoActionPerformed

    private void tovehregnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehregnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tovehregnoActionPerformed

    private void tovehimg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehimg1ActionPerformed

        String path1 = null;

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path1 = f.getAbsolutePath();
        pathimg1 = path1;
        // System.out.println(path1);
        try {
            BufferedImage bi = ImageIO.read(new File(path1));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);

        } catch (Exception ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }

        pb = new PBThread(tovehpbar);
        pb.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_tovehimg1ActionPerformed

    private void tovehimg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehimg2ActionPerformed

        String path2 = null;

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path2 = f.getAbsolutePath();
        pathimg2 = path2;
        // System.out.println(path2);
        try {
            BufferedImage bi = ImageIO.read(new File(path2));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);

        } catch (Exception ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }

        pb = new PBThread(tovehpbar);
        pb.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_tovehimg2ActionPerformed

    private void tovehimg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehimg3ActionPerformed

        String path3 = null;

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path3 = f.getAbsolutePath();
        pathimg3 = path3;
        //System.out.println(path3);
        try {
            BufferedImage bi = ImageIO.read(new File(path3));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);

        } catch (Exception ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }

        pb = new PBThread(tovehpbar);
        pb.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_tovehimg3ActionPerformed

    private void tovehimg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehimg4ActionPerformed

        String path4 = null;

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path4 = f.getAbsolutePath();
        pathimg4 = path4;
        // System.out.println(path4);
        try {
            BufferedImage bi = ImageIO.read(new File(path4));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);

        } catch (Exception ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }

        pb = new PBThread(tovehpbar);
        pb.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_tovehimg4ActionPerformed

    private void tovehsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehsubActionPerformed

        DefaultTableModel model = (DefaultTableModel)totable.getModel();

        db1 = new ParabitDB();
        try{
            String vsattribute = "`TOID`, `VehicleType`, `VehicleNo`, `VehicleModel`, `FuelType`, `VehRegNo`, `RegExpDate`, `VehInsNo`, `InsExpDate`, `Capacity`, Image1, Image2, Image3, Image4, `VehRegDate`, POID, PCode";
            System.out.println(vsattribute);

            for(int i =0; i<model.getRowCount(); i++){
                String vehtype = model.getValueAt(i, 1).toString();
                String vehno = model.getValueAt(i, 2).toString();
                String vehmodel = model.getValueAt(i, 3).toString();
                String fueltype = model.getValueAt(i, 4).toString();
                String regnodt = model.getValueAt(i, 5).toString();
                String insnodt = model.getValueAt(i, 6).toString();
                String cap = model.getValueAt(i, 7).toString();
                String img = model.getValueAt(i, 8).toString();

                String[] reg = regnodt.split(", ");
                String[] ins = insnodt.split(", ");

                String[] image = img.split(",  ");

                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
                LocalDateTime now = LocalDateTime.now();
                String date = (dtf.format(now));

                String vsvalue = toid+"','"+vehtype+"','"+vehno+"','"+vehmodel+"','"+fueltype+"','"+reg[0]+"','"+reg[1]+"','"+ins[0]+"','"+ins[1]+"','"+cap+"',?"+",?"+",?"+",?,'"+date+"','"+poid+"','"+pcode;
                 System.out.println(vsvalue);

                String qvs = "insert into vehicledetails ("+vsattribute+") values('"+vsvalue+"')";
                System.out.println(qvs);

                db1.pst = db1.con.prepareStatement(qvs);

                InputStream img1 = new FileInputStream(image[0]);
                InputStream img2 = new FileInputStream(image[1]);
                InputStream img3 = new FileInputStream(image[2]);
                InputStream img4 = new FileInputStream(image[3]);

                db1.pst.setBlob(1, img1);
                db1.pst.setBlob(2, img2);
                db1.pst.setBlob(3, img3);
                db1.pst.setBlob(4, img4);

                db1.pst.executeUpdate();

            }
            //rsm = new Mail(toemail.getText(),toname.getText());
            JOptionPane.showMessageDialog(this,"Registered Successfully!!!");
            PanchayatData pd = new PanchayatData(null,false,poid);
            pd.trans.setVisible(true);
            pd.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_tovehsubActionPerformed

    private void tovehnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehnextActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        String s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,img;
        int sno = 0;

        sno = sno + 1;
        s1 = (String)tovehtype.getSelectedItem();
        s2 = tovehno.getText();
        s3 = tovehmodel.getText();
        s4 = (String)tovehfuel.getSelectedItem();
        s5 = tovehregno.getText();
        s6 = sdf.format(tovehrexdate.getDate());
        s7 = tovehinsno.getText();
        s8 = sdf.format(tovehiexdate.getDate());
        s9 = tovehcap.getText();
        s10 = s5+", "+s6;
        s11 = s7+", "+s8;

        img = pathimg1+",  "+pathimg2+",  "+pathimg3+",  "+pathimg4;

        DefaultTableModel model = (DefaultTableModel)totable.getModel();
        model.addRow(new Object[]{sno,s1,s2,s3,s4,s10,s11,s9,img});

        // TODO add your handling code here:
    }//GEN-LAST:event_tovehnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                String b = null;
                AddVehicle dialog = new AddVehicle(new javax.swing.JFrame(), true,a,b);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable totable;
    private javax.swing.JTextField tovehcap;
    private javax.swing.JComboBox<String> tovehfuel;
    private com.toedter.calendar.JDateChooser tovehiexdate;
    private javax.swing.JButton tovehimg1;
    private javax.swing.JButton tovehimg2;
    private javax.swing.JButton tovehimg3;
    private javax.swing.JButton tovehimg4;
    private javax.swing.JTextField tovehinsno;
    private javax.swing.JTextField tovehmodel;
    private javax.swing.JButton tovehnext;
    private javax.swing.JTextField tovehno;
    private javax.swing.JProgressBar tovehpbar;
    private javax.swing.JTextField tovehregno;
    private com.toedter.calendar.JDateChooser tovehrexdate;
    private javax.swing.JButton tovehsub;
    private javax.swing.JComboBox<String> tovehtype;
    private javax.swing.JLabel transid;
    // End of variables declaration//GEN-END:variables
}
