package Transport;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt TO change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java TO edit this template
 */

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import vegetabletrading.EmpLogin;
import vegetabletrading.HomePage;
import vegetabletrading.ParabitDB;
import vegetabletrading.ScreenSize;

/**
 *
 * @author HARSHIT
 */
public class TO extends javax.swing.JFrame {
    String toid,date,scode;
    ParabitDB db1;
    /**
     * Creates new form MandiOperator
     */
    public TO(String a) {
        initComponents();
        a = "1";
        toid = a;
        regveh.setVisible(false);
        allotveh.setVisible(false);
                
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDateTime now = LocalDateTime.now();  
        date = (dtf.format(now));
        
        ScreenSize s = new ScreenSize();
        this.setSize(s.width, s.height);
        
        getData();
          
    }
    
    private void getData(){
        String pcode = null;
        transoid.setText("Owner Id : "+toid);
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select * from transportowner where TOID = "+toid);
            db1.rs.next();
            String name = db1.rs.getString("TOName");
            transoname.setText("Owner Name : "+name); 
            
            BufferedImage bi = ImageIO.read(db1.rs.getBinaryStream("TOPhoto"));
            Image img = bi.getScaledInstance(112, 126, Image.SCALE_SMOOTH );
            toimg.setIcon(new ImageIcon(img));
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select PCode from transportowner where TOID = "+toid);
            db1.rs.next();
            pcode = db1.rs.getString(1);
            panchcode.setText("Panchayat Code : "+pcode);            
        }catch(Exception e)
        {
            System.out.println(e);
        }  
        
        //to get employee post state code
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select StateCode from employee where PostingID = "+pcode);
            while(db1.rs.next())
            {
                scode = db1.rs.getString(1);
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        transoid = new javax.swing.JLabel();
        panchcode = new javax.swing.JLabel();
        transoname = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        regveh = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        vehtable = new javax.swing.JTable();
        vehtype = new javax.swing.JTextField();
        vehno = new javax.swing.JTextField();
        vehmodel = new javax.swing.JTextField();
        vehstatus = new javax.swing.JTextField();
        fueltype = new javax.swing.JTextField();
        cap = new javax.swing.JTextField();
        statusbt = new javax.swing.JButton();
        note = new javax.swing.JTextField();
        allotveh = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        alotvehtabel = new javax.swing.JTable();
        toimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(106, 200, 43));

        jButton3.setBackground(new java.awt.Color(106, 200, 43));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Registered Vehicle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setText("  VEGETABLE TRADING");

        jButton4.setBackground(new java.awt.Color(106, 200, 43));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Alloted Vehicle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel2.setBackground(new java.awt.Color(106, 200, 43));

        transoid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        panchcode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        transoname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton1.setBackground(java.awt.SystemColor.activeCaption);
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("TRANSPORT OWNER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transoid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transoname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(panchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(transoid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transoname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        regveh.setBackground(new java.awt.Color(255, 255, 255));
        regveh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regveh.setPreferredSize(new java.awt.Dimension(867, 420));

        vehtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S No.", "Vehicle Type", "Vehicle No.", "Vehicle Model ", "Fuel Type", "Capacity", "Status", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vehtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehtableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(vehtable);

        vehtype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vehtype.setText("Vehicle Type");
        vehtype.setBorder(null);

        vehno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vehno.setText("Vehicle No.");
        vehno.setBorder(null);

        vehmodel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vehmodel.setText("Vehicle Model");
        vehmodel.setBorder(null);

        vehstatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vehstatus.setText("Status");
        vehstatus.setBorder(null);

        fueltype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fueltype.setText("Fuel Type");
        fueltype.setBorder(null);

        cap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cap.setText("Capacity");
        cap.setBorder(null);

        statusbt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusbt.setText("OFF");
        statusbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusbtActionPerformed(evt);
            }
        });

        note.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        note.setText("Note");

        javax.swing.GroupLayout regvehLayout = new javax.swing.GroupLayout(regveh);
        regveh.setLayout(regvehLayout);
        regvehLayout.setHorizontalGroup(
            regvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regvehLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(regvehLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(regvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(regvehLayout.createSequentialGroup()
                        .addComponent(note, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(statusbt))
                    .addGroup(regvehLayout.createSequentialGroup()
                        .addGroup(regvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fueltype)
                            .addComponent(vehtype, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(regvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cap)
                            .addComponent(vehno, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addGroup(regvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vehmodel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(vehstatus))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        regvehLayout.setVerticalGroup(
            regvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regvehLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(regvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(regvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fueltype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(regvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusbt)
                    .addComponent(note, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        allotveh.setBackground(new java.awt.Color(255, 255, 255));
        allotveh.setPreferredSize(new java.awt.Dimension(867, 420));

        alotvehtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S No.", "Vehicle Type", "Vehicle No.", "Fuel Type", "Capacity", "Price", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        alotvehtabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alotvehtabelMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(alotvehtabel);

        javax.swing.GroupLayout allotvehLayout = new javax.swing.GroupLayout(allotveh);
        allotveh.setLayout(allotvehLayout);
        allotvehLayout.setHorizontalGroup(
            allotvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allotvehLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        allotvehLayout.setVerticalGroup(
            allotvehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allotvehLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(regveh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(allotveh, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regveh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(allotveh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regveh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(allotveh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        toimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toimg, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(toimg, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        HomePage hpob = new HomePage();
        hpob.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        regveh.setVisible(true);
        allotveh.setVisible(false);
        vehtype.setVisible(false);
        vehno.setVisible(false);
        vehmodel.setVisible(false);
        vehstatus.setVisible(false);
        fueltype.setVisible(false);
        cap.setVisible(false);
        statusbt.setVisible(false);
        note.setVisible(false);
        
        vehtype.setEditable(false);
        vehno.setEditable(false);
        vehmodel.setEditable(false);
        vehstatus.setEditable(false);
        fueltype.setEditable(false);
        cap.setEditable(false);        
        note.setEditable(false);
        
        //for vehicle details
        try {
            String sql = ("SELECT * FROM `vehicledetails` WHERE TOID = '"+ toid +"';");
            db1 = new ParabitDB();
            
            DefaultTableModel model = (DefaultTableModel)vehtable.getModel();
            model.setRowCount(0);
            
            db1.rs = db1.stm.executeQuery(sql);
            int sno = 0;
            //to set date got from data base for transport owner vehicles
            while(db1.rs.next())
            {
                sno = sno + 1;
                String vehtype = db1.rs.getString("VehicleType");
                String vehno = db1.rs.getString("VehicleNo");
                String vehmodel = db1.rs.getString("VehicleModel");
                String fueltype = db1.rs.getString("FuelType");
                String cap = db1.rs.getString("Capacity");
                String status;
                if(db1.rs.getString("Status").equals("1")){
                    status = "ON";
                }else{
                    status = "OFF";
                }                
                String note = db1.rs.getString("Note");
                 
                model.addRow(new Object[]{sno,vehtype,vehno,vehmodel,fueltype,cap,status,note});
            }  
        } catch (Exception e)
        {
            System.out.println(e);      
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void vehtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehtableMouseClicked
        int i = vehtable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)vehtable.getModel();
        
        vehtype.setText("Vehicle Type: "+ model.getValueAt(i, 1).toString());
        vehno.setText("Vehicle No.: "+ model.getValueAt(i, 2).toString());
        vehmodel.setText("Vehicle Model: "+ model.getValueAt(i, 3).toString());
        fueltype.setText("Fuel Type: "+ model.getValueAt(i, 4).toString());
        cap.setText("Capacity: "+ model.getValueAt(i,5).toString()+"Kg");
        vehstatus.setText("Status: "+ model.getValueAt(i, 6).toString());
        statusbt.setText(model.getValueAt(i, 6).toString());
        if(model.getValueAt(i, 6).toString().equals("ON")){
            statusbt.setBackground(Color.GREEN);
        }else{
            statusbt.setBackground(Color.RED);
        }
        
        vehtype.setVisible(true);
        vehno.setVisible(true);
        vehmodel.setVisible(true);
        vehstatus.setVisible(true);
        fueltype.setVisible(true);
        cap.setVisible(true);
                
        if(model.getValueAt(i, 7).toString().equals("OK")){
            note.setVisible(false);
            statusbt.setVisible(true);
        }else{
            statusbt.setVisible(false);
            note.setText("Note: "+model.getValueAt(i, 7).toString());
            note.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_vehtableMouseClicked

    private void statusbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusbtActionPerformed
        String vno[] = vehno.getText().split(": ");
        String vstatus[] = vehstatus.getText().split(": ");
        
        if(vstatus[1].equals("ON")){
            db1 = new ParabitDB();
            try{
                String update = "UPDATE `vehicledetails` SET `Status` = '0' WHERE `TOID`= "+toid+"  and VehicleNo = '"+ vno[1] +"';";
                //System.out.println(update);
                db1.stm.executeUpdate(update);
                
                String delete = "DELETE FROM `availveh"+scode+"` WHERE VehicleNo = '"+ vno[1] +"';";
                System.out.println(delete);
                db1.stm.executeUpdate(delete);
                
                vehstatus.setText("Status: OFF");
                statusbt.setText("OFF");
                statusbt.setBackground(Color.RED);
            }catch(Exception e)
            {
                System.out.println(e);
            }
        }else{
            db1 = new ParabitDB();
            try{
                String update = "UPDATE `vehicledetails` SET `Status` = '1' WHERE `TOID`= "+toid+"  and VehicleNo = '"+ vno[1] +"';";
                //System.out.println(update);
                db1.stm.executeUpdate(update);
                
                vehstatus.setText("Status: ON");
                statusbt.setText("ON");
                statusbt.setBackground(Color.GREEN);
            }catch(Exception e)
            {
                System.out.println(e);
            }
        }
        
        //for refreshing vehicle details
        try {
            String sql = ("SELECT * FROM `vehicledetails` WHERE TOID = '"+ toid +"';");
            db1 = new ParabitDB();
            
            DefaultTableModel model = (DefaultTableModel)vehtable.getModel();
            model.setRowCount(0);
            
            db1.rs = db1.stm.executeQuery(sql);
            int sno = 0;
            //to set date got from data base for transport owner vehicles
            while(db1.rs.next())
            {
                sno = sno + 1;
                String vehtype = db1.rs.getString("VehicleType");
                String vehno = db1.rs.getString("VehicleNo");
                String vehmodel = db1.rs.getString("VehicleModel");
                String fueltype = db1.rs.getString("FuelType");
                String cap = db1.rs.getString("Capacity");
                String status;
                if(db1.rs.getString("Status").equals("1")){
                    status = "ON";
                }else{
                    status = "OFF";
                }                
                String note = db1.rs.getString("Note");
                 
                model.addRow(new Object[]{sno,vehtype,vehno,vehmodel,fueltype,cap,status,note});
            }  
        } catch (Exception e)
        {
            System.out.println(e);      
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_statusbtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        regveh.setVisible(false);
        allotveh.setVisible(true);
        
        try {
            String sql = "SELECT * FROM `allotedveh23` WHERE TOID = '"+ toid +"';";
            db1 = new ParabitDB();
            System.out.println(sql);
            
            DefaultTableModel model = (DefaultTableModel)alotvehtabel.getModel();
            model.setRowCount(0);
            
            db1.rs = db1.stm.executeQuery(sql);
            int sno = 0;
            //to set date got from data base for transport owner vehicles
            while(db1.rs.next())
            {
                sno = sno + 1;
                String vehtype = db1.rs.getString("VehicleType");
                String vehno = db1.rs.getString("VehicleNo");
                String fueltype = db1.rs.getString("FuelType");
                int weightallot = db1.rs.getInt("WeightAlloted");
                int price = db1.rs.getInt("Rate");
                int TotalPrice = weightallot * price;
                 
                model.addRow(new Object[]{sno,vehtype,vehno,fueltype,weightallot,TotalPrice});
            }  
        } catch (Exception e)
        {
            System.out.println(e);      
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void alotvehtabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alotvehtabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_alotvehtabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                new TO(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allotveh;
    private javax.swing.JTable alotvehtabel;
    private javax.swing.JTextField cap;
    private javax.swing.JTextField fueltype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField note;
    private javax.swing.JLabel panchcode;
    private javax.swing.JPanel regveh;
    private javax.swing.JButton statusbt;
    private javax.swing.JLabel toimg;
    private javax.swing.JLabel transoid;
    private javax.swing.JLabel transoname;
    private javax.swing.JTextField vehmodel;
    private javax.swing.JTextField vehno;
    private javax.swing.JTextField vehstatus;
    private javax.swing.JTable vehtable;
    private javax.swing.JTextField vehtype;
    // End of variables declaration//GEN-END:variables
}
