/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package panchayatoperator;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.table.DefaultTableModel;
import vegetabletrading.ParabitDB;

/**
 *
 * @author HARSHIT
 */
public class AllotVehicle extends javax.swing.JDialog {
    ParabitDB db1;
    String toid,date,pcode;
    int totalweight = 0;
    
    /**
     * Creates new form AllotVehicle
     */
    public AllotVehicle(java.awt.Frame parent, boolean modal, String a,int b) {
        super(parent, modal);
        initComponents();
        pcode = a;
        totalweight = b;
        tweight.setText("Total Weight: "+totalweight+" KG");
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDateTime now = LocalDateTime.now();  
        date = (dtf.format(now));
        
        getData();
    }
    
    private void getData(){
        
        try {
            String sql = "SELECT * FROM `vehicledetails` WHERE PCode = '"+ pcode +"' and Status = '1' ORDER BY Capacity;";
            System.out.println(sql);
                        
            db1 = new ParabitDB();
            
            DefaultTableModel model = (DefaultTableModel)alotvehtable.getModel();
            model.setRowCount(0);
            db1.rs = db1.stm.executeQuery(sql);
            int sno = 0;
            while(db1.rs.next())
            {
                sno = sno + 1;
                String vehtype = db1.rs.getString("VehicleType");
                String vehno = db1.rs.getString("VehicleNo");
                String vehmodel = db1.rs.getString("VehicleModel");
                String fueltype = db1.rs.getString("FuelType");
                int cap = Integer.parseInt(db1.rs.getString("Capacity"));
                String price = db1.rs.getString("Price");
                 
                model.addRow(new Object[]{sno,vehno,vehtype,vehmodel,fueltype,cap,price});
            }  
        } catch (Exception e)
        {
            System.out.println(e);      
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        alotvehtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        tweight = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));

        alotvehtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S No.", "Vehicle No.", "Vehicle Type", "Vehicle Model ", "Fuel Type", "Capacity", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        alotvehtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alotvehtableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(alotvehtable);

        jButton1.setText("ALLOT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tweight.setText("Total Weight");
        tweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tweight, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alotvehtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alotvehtableMouseClicked
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_alotvehtableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)alotvehtable.getModel();
               
        int vehnoarr[] = new int[model.getRowCount()];
        int index = -1;
        for(int i =0; i<model.getRowCount(); i++){
            int cap = Integer.parseInt(model.getValueAt(i,5).toString());
            System.out.println(cap); 
            System.out.println(totalweight);
            if(totalweight <= cap){
                index = index + 1;
                vehnoarr[0] = cap;
            }
        }
        if(vehnoarr[0]==0){
            index = model.getRowCount();
        }
        
        index = ThreadLocalRandom.current().nextInt(0, index+1);
        String vehno = model.getValueAt(index,1).toString();
        
        System.out.println(vehno);
        
        
        
        model.removeRow(index);
        
        if(model.getRowCount() == 0){
            getData();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tweightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllotVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllotVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllotVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllotVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                int b = 0;
                AllotVehicle dialog = new AllotVehicle(new javax.swing.JFrame(), true,a,b);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alotvehtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField tweight;
    // End of variables declaration//GEN-END:variables
}
