/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mandioperator;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import vegetabletrading.Mail;
import vegetabletrading.ParabitDB;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HARSHIT
 */
public class MandiDataMS extends javax.swing.JFrame {
    ParabitDB db1;
    int emailotp;
    String postid = null,date,empid;
    Mail vm;
    
    /**
     * Creates new form MandiDataWS
     */
    public MandiDataMS(String a) {
        initComponents();
        empid = a;
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDateTime now = LocalDateTime.now();  
        date = (dtf.format(now));
        
        getData();
        
        try
        {                        
            db1 = new ParabitDB();
            db1.rs = db1.stm.executeQuery("SELECT * FROM `messreg` WHERE MandiCode = '"+ postid +"' ORDER BY MessID;");            
                      
            //to set date got from data base and set to product table
            while(db1.rs.next())
            {
                String messid = String.valueOf(db1.rs.getInt("MessID"));
                String messname = db1.rs.getString("MessName");
                String messcate = db1.rs.getString("MessCat");
                String messtype = db1.rs.getString("MessType");
                String messcap = db1.rs.getString("MessCap");
                String messregmob = db1.rs.getString("RegMobNo");
                String messaltmob = db1.rs.getString("MobNo");
                String messemailid = db1.rs.getString("EmailID");
                String messadd = db1.rs.getString("HouseNo")+", "+db1.rs.getString("Street")+", "+db1.rs.getString("Colony")+", "+db1.rs.getString("CityVillage")+", "+db1.rs.getString("Block")+", "+db1.rs.getString("Tehsil")+", "+db1.rs.getString("Dist")+", "+db1.rs.getString("State")+", "+db1.rs.getString("Pincode");
                                                         
                DefaultTableModel promodel = (DefaultTableModel)wtable.getModel();
                promodel.addRow(new Object[]{messid,messname,messcate,messtype,messcap,messregmob,messaltmob,messemailid,messadd});
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    private void getData(){
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select PostingID from employee where empid = "+empid);
            db1.rs.next();
            postid = db1.rs.getString(1);
                        
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select statename from statecode order by statename");
            
            while(db1.rs.next())
            {
                mdstate.addItem(db1.rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wholesaler = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        wholesalerdef = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        wtable = new javax.swing.JTable();
        wholesalerpanel = new javax.swing.JPanel();
        mtb = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        moiname = new javax.swing.JTextField();
        moidob = new javax.swing.JTextField();
        moiregmob = new javax.swing.JTextField();
        moialtmob = new javax.swing.JTextField();
        moiaadhar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        moipan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        moiemail = new javax.swing.JTextField();
        moiphoto = new javax.swing.JLabel();
        moisign = new javax.swing.JLabel();
        moiphupload = new javax.swing.JButton();
        moisignupload = new javax.swing.JButton();
        moinext = new javax.swing.JButton();
        moiid = new javax.swing.JLabel();
        moiotp = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        Verify = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        mdhouse = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        mdstreet = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mdcolony = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mdvillage = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        mdblock = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        mdtehsil = new javax.swing.JTextField();
        mdpincode = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        mddistrict = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        mdstate = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        moiupdate = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        mdname = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        mdcate = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        mdtype = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        mdcap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        empmid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wholesaler.setBackground(new java.awt.Color(255, 255, 255));
        wholesaler.setMinimumSize(new java.awt.Dimension(1170, 478));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("   Mess Details ");

        jLayeredPane2.setPreferredSize(new java.awt.Dimension(1159, 419));

        wholesalerdef.setBackground(new java.awt.Color(255, 255, 255));
        wholesalerdef.setMaximumSize(new java.awt.Dimension(1154, 391));
        wholesalerdef.setMinimumSize(new java.awt.Dimension(1154, 391));
        wholesalerdef.setPreferredSize(new java.awt.Dimension(1155, 415));

        wtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mess Name", "Mess Category", "Mess Type", "Mess Capacity", "Reg Mob", "Alt Mob", "Email ID", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(wtable);
        if (wtable.getColumnModel().getColumnCount() > 0) {
            wtable.getColumnModel().getColumn(0).setResizable(false);
            wtable.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        javax.swing.GroupLayout wholesalerdefLayout = new javax.swing.GroupLayout(wholesalerdef);
        wholesalerdef.setLayout(wholesalerdefLayout);
        wholesalerdefLayout.setHorizontalGroup(
            wholesalerdefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1159, Short.MAX_VALUE)
            .addGroup(wholesalerdefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wholesalerdefLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1149, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        wholesalerdefLayout.setVerticalGroup(
            wholesalerdefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
            .addGroup(wholesalerdefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wholesalerdefLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        wholesalerpanel.setBackground(new java.awt.Color(204, 255, 204));
        wholesalerpanel.setMaximumSize(new java.awt.Dimension(1154, 391));
        wholesalerpanel.setMinimumSize(new java.awt.Dimension(1154, 391));
        wholesalerpanel.setPreferredSize(new java.awt.Dimension(1155, 415));

        mtb.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Alt Mob No.");

        jLabel5.setText("Reg Mob No.");

        jLabel6.setText("DOB");

        jLabel7.setText("Name");

        jLabel8.setText("Mess ID :");

        jLabel9.setText("Aadhar No.");

        jLabel10.setText("Pan No.");

        jLabel11.setText("Email ID");

        moiphoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        moiphoto.setText("           Photo");
        moiphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        moiphoto.setPreferredSize(new java.awt.Dimension(134, 172));
        moiphoto.setVerifyInputWhenFocusTarget(false);

        moisign.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        moisign.setText("           Signature");
        moisign.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        moisign.setPreferredSize(new java.awt.Dimension(151, 50));
        moisign.setVerifyInputWhenFocusTarget(false);

        moiphupload.setText("Upload");
        moiphupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moiphuploadActionPerformed(evt);
            }
        });

        moisignupload.setText("Upload");
        moisignupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moisignuploadActionPerformed(evt);
            }
        });

        moinext.setText("Next");
        moinext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moinextActionPerformed(evt);
            }
        });

        jLabel61.setText("Otp :");

        Verify.setText("Verify");
        Verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyActionPerformed(evt);
            }
        });

        jButton7.setText("Send OTP");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moiname, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(moidob)
                    .addComponent(moiregmob)
                    .addComponent(moialtmob)
                    .addComponent(moiid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moiaadhar)
                    .addComponent(moipan)
                    .addComponent(moiemail, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(moiotp))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(moiphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(moisign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(moisignupload)
                                .addGap(72, 72, 72))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Verify, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(63, 63, 63)
                                .addComponent(moiphupload)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(moinext)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(moiid, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(moiname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(moiaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(moidob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(moipan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(moiregmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(moiemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(moialtmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61)
                            .addComponent(moiotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Verify)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(moiphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(moisign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(moisignupload)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moiphupload)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(moinext)
                .addGap(40, 40, 40))
        );

        mtb.addTab("Owner Information", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("House No.");

        jLabel16.setText("Street");

        jLabel14.setText("Colony");

        mdcolony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdcolonyActionPerformed(evt);
            }
        });

        jLabel13.setText("City/Village");

        jLabel17.setText("Block");

        mdblock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdblockActionPerformed(evt);
            }
        });

        jLabel15.setText("Tehsil");

        jLabel19.setText("PinCode");

        mddistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose District" }));
        mddistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mddistrictActionPerformed(evt);
            }
        });

        jLabel21.setText("District");

        mdstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose State" }));
        mdstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdstateActionPerformed(evt);
            }
        });

        jLabel18.setText("State");

        moiupdate.setText("Update");
        moiupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moiupdateActionPerformed(evt);
            }
        });

        jLabel20.setText("Mess Name");

        mdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdnameActionPerformed(evt);
            }
        });

        jLabel22.setText("Mess Category");

        mdcate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Mess Category", "Government", "Private" }));

        jLabel30.setText("Mess Type");

        mdtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Mess Type", "Student", "Employee" }));

        jLabel31.setText("Mess Capacity");

        jLabel2.setText("Address :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(moiupdate)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mdcap, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mdstate, 0, 180, Short.MAX_VALUE)
                                        .addComponent(mdhouse)
                                        .addComponent(mdvillage)
                                        .addComponent(mdname, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mddistrict, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mdblock)
                                        .addComponent(mdstreet)
                                        .addComponent(mdcate, 0, 180, Short.MAX_VALUE))
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mdtehsil)
                                        .addComponent(mdpincode)
                                        .addComponent(mdcolony)
                                        .addComponent(mdtype, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(mdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mdcate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(mdtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mdcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(mdhouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mdstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mdcolony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mdvillage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(mdblock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(mdtehsil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(mdstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(mddistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(mdpincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(moiupdate)
                .addGap(30, 30, 30))
        );

        mtb.addTab("Mess Details", jPanel3);

        javax.swing.GroupLayout wholesalerpanelLayout = new javax.swing.GroupLayout(wholesalerpanel);
        wholesalerpanel.setLayout(wholesalerpanelLayout);
        wholesalerpanelLayout.setHorizontalGroup(
            wholesalerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mtb)
        );
        wholesalerpanelLayout.setVerticalGroup(
            wholesalerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mtb)
        );

        jLayeredPane2.setLayer(wholesalerdef, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(wholesalerpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholesalerdef, javax.swing.GroupLayout.DEFAULT_SIZE, 1159, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(wholesalerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1159, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholesalerdef, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(wholesalerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
        );

        jLabel3.setText("Mess  ID");

        jButton5.setText("Get");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel37.setText(" MANDI DATA");
        jLabel37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wholesalerLayout = new javax.swing.GroupLayout(wholesaler);
        wholesaler.setLayout(wholesalerLayout);
        wholesalerLayout.setHorizontalGroup(
            wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholesalerLayout.createSequentialGroup()
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(empmid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton5))
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addGap(526, 526, 526)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wholesalerLayout.createSequentialGroup()
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addGap(508, 508, 508)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 425, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(21, 21, 21))
        );
        wholesalerLayout.setVerticalGroup(
            wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholesalerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholesaler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholesaler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String wrid = empmid.getText();
        try
        {
            String sql = ("SELECT * FROM `wholesalerreg` WHERE WRID = '"+ wrid +"' and MandiCode = '"+ postid +"';");
            //db1 = new ParabitDB();
            //db1.rs = db1.stm.executeQuery(sql);
            db1 = new ParabitDB();
            db1.rs = db1.stm.executeQuery(sql);
            boolean check = db1.rs.next();
            if(check)
            {
                //to set date got from database for pannel
                //while(db1.rs.next())
                String wid = null,wname =null,wdob = null,wregmob = null,waltmob = null,wemailid = null,waadhar = null,wpan = null,whouse = null,wstreet =null,wcolony = null,wcity = null,wblock = null,wtehsil = null,wdist = null,wstate = null,wpincode = null,wlandsize = null,wirr = null,waed = null,wped = null,wted = null,wexp = null,wbank = null,wbranch = null,waccno = null,wifsc = null;
       
                wid = String.valueOf(db1.rs.getInt("WRID"));
                wname = db1.rs.getString("WRName");
                waadhar = db1.rs.getString("AadharNo");
                wpan = db1.rs.getString("PANNo");
                wdob = db1.rs.getString("DOB");
                wregmob = db1.rs.getString("RegMobNo");
                waltmob = db1.rs.getString("MobNo");
                wemailid = db1.rs.getString("EmailIDOff");
                BufferedImage pbi = ImageIO.read(db1.rs.getBinaryStream("WRPhoto"));
                Image pimg = pbi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
                BufferedImage sbi = ImageIO.read(db1.rs.getBinaryStream("Signature"));
                Image simg = sbi.getScaledInstance(151, 50, Image.SCALE_SMOOTH );
                waccno = db1.rs.getString("BAccNo");
                wbank = db1.rs.getString("BName");
                wifsc = db1.rs.getString("BIFSC");
                wbranch = db1.rs.getString("BBranch");
                waed = db1.rs.getString("WRAEdu");
                wped = db1.rs.getString("WRPEdu");
                wted = db1.rs.getString("WRTEdu");
                wexp = db1.rs.getString("WRExp");
                whouse = db1.rs.getString("HouseNo");
                wstreet = db1.rs.getString("Street");
                wcolony = db1.rs.getString("Colony");
                wcity = db1.rs.getString("CityVillage");
                wblock = db1.rs.getString("Block");
                wtehsil = db1.rs.getString("Tehsil");
                wdist = db1.rs.getString("Dist");
                wstate = db1.rs.getString("State");
                wpincode = db1.rs.getString("Pincode");
                
                moiid.setText(wid);
                moiname.setText(wname);
                moidob.setText(wdob);
                moiregmob.setText(wregmob);
                moialtmob.setText(waltmob);
                moiemail.setText(wemailid);
                moiaadhar.setText(waadhar);
                moipan.setText(wpan);
                moiphoto.setIcon(new ImageIcon(pimg));
                moisign.setIcon(new ImageIcon(simg));
                mdhouse.setText(whouse);
                mdstreet.setText(wstreet);
                mdcolony.setText(wcolony);
                mdvillage.setText(wcity);
                mdblock.setText(wblock);
                mdtehsil.setText(wtehsil);
                mdstate.setSelectedItem(wstate);
                mddistrict.setSelectedItem(wdist);
                mdpincode.setText(wpincode);
                mdname.setEditable(false);
                mdcap.setEditable(false);
                mdcate.setEditable(false);
                mdtype.setEditable(false);
                
                wholesalerdef.setVisible(false);
                wholesalerpanel.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "WholeSaler Id "+wrid+" not found...");
                wholesalerdef.setVisible(true);
                wholesalerpanel.setVisible(false);
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        moiname.setEditable(false);
        moidob.setEditable(false);
        moiregmob.setEditable(false);
        moialtmob.setEditable(false);
        moiemail.setEditable(false);
        moiaadhar.setEditable(false);
        moipan.setEditable(false);
        mdhouse.setEditable(false);
        mdstreet.setEditable(false);
        mdcolony.setEditable(false);
        mdvillage.setEditable(false);
        mdblock.setEditable(false);
        mdtehsil.setEditable(false);
        mdstate.setEditable(false);
        mddistrict.setEditable(false);
        mdpincode.setEditable(false);
        mdname.setEditable(false);
        mdcap.setEditable(false);
        mdcate.setEditable(false);
        mdtype.setEditable(false);
        
        
        moinext.setVisible(false);
        moiupdate.setVisible(false);
        moiphupload.setVisible(false);
        moisignupload.setVisible(false);
        
        mtb.setSelectedIndex(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void moiupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moiupdateActionPerformed

        String s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,wid;

        wid = moiid.getText();
        
        s1 = mdname.getText();
        s2 = mdcap.getText();
        s3 = (String)mdcate.getSelectedItem();
        s4 = (String)mdtype.getSelectedItem();
        s5 = mdhouse.getText();
        s6 = mdstreet.getText();
        s7 = mdcolony.getText();
        s8 = mdvillage.getText();
        s9 = mdblock.getText();
        s10 = mdtehsil.getText();
        s11 = (String)mdstate.getSelectedItem();
        s12 = (String)mddistrict.getSelectedItem();
        s13 = mdpincode.getText();

        String sql = "UPDATE wholesalerreg SET HouseNo ='"+s1+"', Street ='"+s2+"', Colony ='"+s3+"', CityVillage ='"+s4+"', Block ='"+s5+"', Tehsil ='"+s6+"', State ='"+s7+"', Dist ='"+s8+"', Pincode ='"+s9+"', UpdationDate ='"+date+"' where WRID = " + wid;
        //System.out.println(sql);

        
        db1 = new ParabitDB();
        try
        {
            db1.stm.executeUpdate(sql);
            JOptionPane.showMessageDialog(this,"Updated Sucessfully...");

        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }

        int i = mtb.getSelectedIndex();
        mtb.setSelectedIndex(i+1);
        // TODO add your handling code here:
    }//GEN-LAST:event_moiupdateActionPerformed

    private void mdstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdstateActionPerformed

        String state = mdstate.getSelectedItem().toString();

        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select distinct distname from districtcode where statecode = (select statecode from statecode where statename = '" + state + "') order by distname");

            while(db1.rs.next())
            {
                mddistrict.addItem(db1.rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_mdstateActionPerformed

    private void mddistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mddistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mddistrictActionPerformed

    private void mdblockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdblockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdblockActionPerformed

    private void mdcolonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdcolonyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdcolonyActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String email = moiemail.getText();

        if(email!= "null")
        {
            vm = new Mail(email);
            emailotp = vm.oneTimePass();
            System.out.println(emailotp);
        }
        else{
            JOptionPane.showMessageDialog(this,"Enter valid email...");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void VerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyActionPerformed

        int otpval = Integer.parseInt(moiotp.getText());
        try
        {
            if(otpval==emailotp){
                JOptionPane.showMessageDialog(null,"OTP Verified...");

                moiname.setEditable(true);
                moidob.setEditable(true);
                moiregmob.setEditable(true);
                moialtmob.setEditable(true);
                moiemail.setEditable(true);
                moiaadhar.setEditable(true);
                moipan.setEditable(true);
                mdhouse.setEditable(true);
                mdstreet.setEditable(true);
                mdcolony.setEditable(true);
                mdvillage.setEditable(true);
                mdblock.setEditable(true);
                mdtehsil.setEditable(true);
                mdstate.setEditable(true);
                mddistrict.setEditable(true);
                mdpincode.setEditable(true);
                mdname.setEditable(true);
                mdcap.setEditable(true);
                mdcate.setEditable(true);
                mdtype.setEditable(true);

                moinext.setVisible(true);
                moiupdate.setVisible(true);
                moiphupload.setVisible(true);
                moisignupload.setVisible(true);

            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Valid OTP!!!");
            }

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_VerifyActionPerformed

    private void moinextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moinextActionPerformed

        String s1,s2,s3,s4,s5,s6,s7,s8,wid;

        wid = moiid.getText();
        s2 = moiname.getText();
        s3 = moidob.getText();
        s4 = moiregmob.getText();
        s5 = moialtmob.getText();
        s6 = moiaadhar.getText();
        s7 = moipan.getText();
        s8 = moiemail.getText();
        //s9 = "hi";

        String sql = "UPDATE `wholesalerreg` SET WRName ='"+s2+"', DOB ='"+s3+"', RegMobNo ='"+s4+"', MobNo ='"+s5+"', AadharNo ='"+s6+"', PANNo ='"+s7+"', EmailIdOff ='"+s8+"', UpdationDate ='"+date+"' where WRID = " + wid;
        //System.out.println(sql);

        db1 = new ParabitDB();
        try
        {
            db1.stm.executeUpdate(sql);

        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }

        int i = mtb.getSelectedIndex();
        mtb.setSelectedIndex(i+1);
        // TODO add your handling code here:
    }//GEN-LAST:event_moinextActionPerformed

    private void moisignuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moisignuploadActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String wpathsign = f.getAbsolutePath();

        try {
            BufferedImage bi = ImageIO.read(new File(wpathsign));
            Image im = bi.getScaledInstance(151, 50, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(im);
            moisign.setIcon(icon);

            // TODO add your handling code here:
        } catch (Exception e) {
            System.out.println(e);
        }

        String query = "UPDATE `wholesalerreg` SET Signature = ?";
        db1 = new ParabitDB();
        try {
            db1.pst = db1.con.prepareStatement(query);

            InputStream sign = new FileInputStream(wpathsign);

            db1.pst.setBlob(1, sign);

            db1.pst.executeUpdate();

            // TODO add your handling code here:
        } catch (Exception e) {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_moisignuploadActionPerformed

    private void moiphuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moiphuploadActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String wpathimg = f.getAbsolutePath();

        try {
            BufferedImage bi = ImageIO.read(new File(wpathimg));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            moiphoto.setIcon(icon);

            // TODO add your handling code here:
        } catch (Exception e) {
            System.out.println(e);
        }

        String query = "UPDATE `wholesalerreg` SET WRphoto = ?";
        db1 = new ParabitDB();
        try {
            db1.pst = db1.con.prepareStatement(query);

            InputStream img = new FileInputStream(wpathimg);

            db1.pst.setBlob(1, img);

            db1.pst.executeUpdate();

            // TODO add your handling code here:
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_moiphuploadActionPerformed

    private void mdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mdnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        empmid.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MandiDataMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MandiDataMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MandiDataMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MandiDataMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                new MandiDataMS(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Verify;
    private javax.swing.JTextField empmid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mdblock;
    private javax.swing.JTextField mdcap;
    private javax.swing.JComboBox<String> mdcate;
    private javax.swing.JTextField mdcolony;
    private javax.swing.JComboBox<String> mddistrict;
    private javax.swing.JTextField mdhouse;
    private javax.swing.JTextField mdname;
    private javax.swing.JTextField mdpincode;
    private javax.swing.JComboBox<String> mdstate;
    private javax.swing.JTextField mdstreet;
    private javax.swing.JTextField mdtehsil;
    private javax.swing.JComboBox<String> mdtype;
    private javax.swing.JTextField mdvillage;
    private javax.swing.JTextField moiaadhar;
    private javax.swing.JTextField moialtmob;
    private javax.swing.JTextField moidob;
    private javax.swing.JTextField moiemail;
    private javax.swing.JLabel moiid;
    private javax.swing.JTextField moiname;
    private javax.swing.JButton moinext;
    private javax.swing.JTextField moiotp;
    private javax.swing.JTextField moipan;
    private javax.swing.JLabel moiphoto;
    private javax.swing.JButton moiphupload;
    private javax.swing.JTextField moiregmob;
    private javax.swing.JLabel moisign;
    private javax.swing.JButton moisignupload;
    private javax.swing.JButton moiupdate;
    private javax.swing.JTabbedPane mtb;
    private javax.swing.JPanel wholesaler;
    private javax.swing.JPanel wholesalerdef;
    private javax.swing.JPanel wholesalerpanel;
    private javax.swing.JTable wtable;
    // End of variables declaration//GEN-END:variables
}
