/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mandioperator;

import javax.swing.JOptionPane;
import vegetabletrading.Mail;
import vegetabletrading.ParabitDB;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HARSHIT
 */
public class MandiDataPL extends javax.swing.JFrame {
    ParabitDB db1;
    Mail vm;
    int emailotp;
    String postid,empid;
    
    /**
     * Creates new form MandiDataWS
     */
    public MandiDataPL(String a, String b) {
        initComponents();
        empid = a;
        postid = b;
        
        getDataToTable();
        
        
    }
    
    private void getDataToTable(){
        try
        {                        
            db1 = new ParabitDB();
            db1.rs = db1.stm.executeQuery("SELECT * FROM `vegetablesource` WHERE MCode = '"+ postid +"' ORDER BY PCode;");            
                      
            //to set date got from data base and set to product table
            while(db1.rs.next())
            {
                String pcode = String.valueOf(db1.rs.getInt("PCode"));
                String pgovid = db1.rs.getString("PGovID");
                String pname = db1.rs.getString("PName");
                String poid = db1.rs.getString("POID");
                String poname = db1.rs.getString("POName");
                String pomob = db1.rs.getString("POMobNo");
                String pno = db1.rs.getString("PanchayatNo");
                
                //String waadhar = db1.rs.getString("AadharNo");
                //String wpan = db1.rs.getString("PANNo");
                String add = (db1.rs.getString("PanchayatNo"))+", "+(db1.rs.getString("Street"))+", "+(db1.rs.getString("Colony"))+", "+(db1.rs.getString("CityVillage"))+", "+(db1.rs.getString("Block"))+", "+(db1.rs.getString("Tehsil"))+", "+(db1.rs.getString("Dist"))+", "+(db1.rs.getString("State"))+", "+(db1.rs.getString("Pincode"));
                
                DefaultTableModel promodel = (DefaultTableModel)pltable.getModel();
                promodel.addRow(new Object[]{pcode,pgovid,pname,poid,poname,pomob,add});
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wholesaler = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        pldef = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pltable = new javax.swing.JTable();
        plpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pcode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        poid = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        poname = new javax.swing.JTextField();
        pgid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        pomobno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pstreet = new javax.swing.JTextField();
        pblock = new javax.swing.JTextField();
        pvillage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pstate = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pdistrict = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pcolony = new javax.swing.JTextField();
        ptehsil = new javax.swing.JTextField();
        ppincode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        poemail = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        plotp = new javax.swing.JTextField();
        Verify1 = new javax.swing.JButton();
        panchid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wholesaler.setBackground(new java.awt.Color(255, 255, 255));
        wholesaler.setMinimumSize(new java.awt.Dimension(1170, 478));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("   Panchayat Linked");

        pldef.setMaximumSize(new java.awt.Dimension(1154, 391));
        pldef.setMinimumSize(new java.awt.Dimension(1154, 391));

        pltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Panchayat code", "Panchayat Gov Id", "Panchayat Name", "POID", "PO Name", "PO Mob No", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pltable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pltableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pltable);
        if (pltable.getColumnModel().getColumnCount() > 0) {
            pltable.getColumnModel().getColumn(6).setPreferredWidth(250);
        }

        javax.swing.GroupLayout pldefLayout = new javax.swing.GroupLayout(pldef);
        pldef.setLayout(pldefLayout);
        pldefLayout.setHorizontalGroup(
            pldefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1187, Short.MAX_VALUE)
            .addGroup(pldefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pldefLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1175, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pldefLayout.setVerticalGroup(
            pldefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
            .addGroup(pldefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pldefLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        plpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Panchayat ID");

        pcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcodeActionPerformed(evt);
            }
        });

        jLabel6.setText("Panchayat Operator ID");

        poid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poidActionPerformed(evt);
            }
        });

        jLabel20.setText("Panchayat Government ID");

        jLabel7.setText("Panchayat Operator Name");

        jLabel4.setText("Panchayat Operator No.");

        jLabel5.setText("Panchayat Name");

        jLabel8.setText("Panchayat No.");

        jLabel16.setText("Street");

        pblock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pblockActionPerformed(evt);
            }
        });

        jLabel9.setText("City/Village");

        jLabel12.setText("State");

        pstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose State" }));
        pstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pstateActionPerformed(evt);
            }
        });

        jLabel21.setText("District");

        jLabel17.setText("Block");

        pdistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose District" }));
        pdistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdistrictActionPerformed(evt);
            }
        });

        jLabel14.setText("Colony");

        jLabel15.setText("Tehsil");

        jLabel19.setText("PinCode");

        jLabel10.setText("Address : ");

        jLabel11.setText("Panchayat Opt Email ID");

        poemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poemailActionPerformed(evt);
            }
        });

        update.setText("Update");

        jButton7.setText("Send OTP");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel61.setText("Otp :");

        Verify1.setText("Verify");
        Verify1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Verify1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plpanelLayout = new javax.swing.GroupLayout(plpanel);
        plpanel.setLayout(plpanelLayout);
        plpanelLayout.setHorizontalGroup(
            plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plpanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(plpanelLayout.createSequentialGroup()
                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(plpanelLayout.createSequentialGroup()
                                .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(plpanelLayout.createSequentialGroup()
                                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                        .addGap(30, 30, 30)
                                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(poemail)
                                            .addComponent(pno)
                                            .addComponent(poid)
                                            .addComponent(pcode)
                                            .addComponent(pvillage)
                                            .addComponent(pstate, 0, 170, Short.MAX_VALUE)))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(plpanelLayout.createSequentialGroup()
                                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pgid, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(pstreet)))
                                    .addGroup(plpanelLayout.createSequentialGroup()
                                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                                        .addGap(30, 30, 30)
                                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(pdistrict, 0, 170, Short.MAX_VALUE)
                                                .addComponent(pblock))
                                            .addComponent(poname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(plpanelLayout.createSequentialGroup()
                                        .addComponent(jButton7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)))))
                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plpanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(plpanelLayout.createSequentialGroup()
                                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                        .addGap(30, 30, 30)
                                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ptehsil, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pcolony, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(ppincode)))
                                    .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(plpanelLayout.createSequentialGroup()
                                .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(plpanelLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                                    .addGroup(plpanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plotp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Verify1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pomobno, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                        .addComponent(pname)))))))
                .addGap(38, 38, 38))
        );
        plpanelLayout.setVerticalGroup(
            plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plpanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(pgid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(poid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(pomobno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel61)
                        .addComponent(plotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Verify1))
                    .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(poemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7)))
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plpanelLayout.createSequentialGroup()
                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel16)
                            .addComponent(pstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(pvillage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(pblock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(pstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(pdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(plpanelLayout.createSequentialGroup()
                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(pcolony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(ptehsil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(plpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(ppincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(update)
                .addGap(29, 29, 29))
        );

        jLayeredPane2.setLayer(pldef, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(plpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pldef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(plpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pldef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(plpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setText("Panchayat Code :");

        jButton5.setText("Get");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel37.setText(" MANDI DATA");
        jLabel37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Link More");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wholesalerLayout = new javax.swing.GroupLayout(wholesaler);
        wholesaler.setLayout(wholesalerLayout);
        wholesalerLayout.setHorizontalGroup(
            wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholesalerLayout.createSequentialGroup()
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(panchid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton5))
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wholesalerLayout.createSequentialGroup()
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3))
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addGap(508, 508, 508)
                        .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(21, 21, 21))
        );
        wholesalerLayout.setVerticalGroup(
            wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholesalerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholesaler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholesaler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String panid = panchid.getText();
        String pangovid =null,panname = null,panoid = null,panoname = null,panomobno = null,panoemailid = null,panno = null,panstreet =null,pancolony = null,pancity = null,panblock = null,pantehsil = null,pandist = null,panstate = null,panpincode = null;
        try
        {
            String sql = ("SELECT * FROM `vegetablesource` WHERE PCode = '"+ panid +"' and MCode = '"+ postid +"';");
            System.out.println(sql);
            db1 = new ParabitDB();
            db1.rs = db1.stm.executeQuery(sql);
            boolean check = db1.rs.next();
            if(check){
                System.out.println(sql);
                //to set date got from data base for farmer
                    System.out.println(sql);
                    pangovid = db1.rs.getString("PGovID");
                    panname = db1.rs.getString("PName");
                    panoid = db1.rs.getString("POID");
                    panoname = db1.rs.getString("POName");
                    panomobno = db1.rs.getString("POMobNo");
                    panoemailid = db1.rs.getString("POEmailID");
                    panno = db1.rs.getString("PanchayatNo");
                    panstreet = db1.rs.getString("Street");
                    pancolony = db1.rs.getString("Colony");
                    pancity = db1.rs.getString("CityVillage");
                    panblock = db1.rs.getString("Block");
                    pantehsil = db1.rs.getString("Tehsil");
                    pandist = db1.rs.getString("Dist");
                    panstate = db1.rs.getString("State");
                    panpincode = db1.rs.getString("Pincode");
                
                    pcode.setText(panid);
                    pgid.setText(pangovid);
                    pname.setText(panname);
                    poid.setText(panoid);
                    poname.setText(panoname);
                    pomobno.setText(panomobno);
                    poemail.setText(panoemailid);
                    pno.setText(panno);
                    pstreet.setText(panstreet);
                    pcolony.setText(pancolony);
                    pvillage.setText(pancity);
                    pblock.setText(panblock);
                    ptehsil.setText(pantehsil);
                    pstate.setSelectedItem(pandist);
                    pdistrict.setSelectedItem(panstate);
                    ppincode.setText(panpincode);
                    
                    pldef.setVisible(false);
                    update.setVisible(false);
                    poemail.setEditable(false);
                    plpanel.setVisible(true);
                
            }else{
                JOptionPane.showMessageDialog(null, "Panchayat Id "+panchid+" not found...");
                pldef.setVisible(true);
                plpanel.setVisible(false);
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        PanchayatLinking ob = new PanchayatLinking(this,true,empid,postid);
        ob.setVisible(true);
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcodeActionPerformed

    private void poidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poidActionPerformed

    private void pblockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pblockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pblockActionPerformed

    private void pstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pstateActionPerformed

        //state = pstate.getSelectedItem().toString();

        db1 = new ParabitDB();
        try
        {
        //    db1.rs = db1.stm.executeQuery("select distinct distname from districtcode where statecode = (select statecode from statecode where statename = '" + state + "') order by distname");

            while(db1.rs.next())
            {
                pdistrict.addItem(db1.rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_pstateActionPerformed

    private void pdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdistrictActionPerformed

    private void poemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poemailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        plpanel.setVisible(false);
        panchid.setText("");
        pldef.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String email = poemail.getText();

        if(email!= "null")
        {
            vm = new Mail(email);
            emailotp = vm.oneTimePass();
            System.out.println(emailotp);
        }
        else{
            JOptionPane.showMessageDialog(this,"Enter valid email...");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Verify1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Verify1ActionPerformed

        int otpval = Integer.parseInt(plotp.getText());
        try
        {
            if(otpval==emailotp){
                JOptionPane.showMessageDialog(null,"OTP Verified...");
                update.setVisible(true);
                poemail.setEditable(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Valid OTP!!!");
            }

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Verify1ActionPerformed

    private void pltableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pltableMouseClicked
        int i = pltable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)pltable.getModel();
        String pid = model.getValueAt(i,0).toString();
        panchid.setText(pid);

        // TODO add your handling code here:
    }//GEN-LAST:event_pltableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MandiDataPL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MandiDataPL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MandiDataPL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MandiDataPL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                String b = null;
                new MandiDataPL(a,b).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Verify1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField panchid;
    private javax.swing.JTextField pblock;
    private javax.swing.JTextField pcode;
    private javax.swing.JTextField pcolony;
    private javax.swing.JComboBox<String> pdistrict;
    private javax.swing.JTextField pgid;
    private javax.swing.JPanel pldef;
    private javax.swing.JTextField plotp;
    private javax.swing.JPanel plpanel;
    private javax.swing.JTable pltable;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pno;
    private javax.swing.JTextField poemail;
    private javax.swing.JTextField poid;
    private javax.swing.JTextField pomobno;
    private javax.swing.JTextField poname;
    private javax.swing.JTextField ppincode;
    private javax.swing.JComboBox<String> pstate;
    private javax.swing.JTextField pstreet;
    private javax.swing.JTextField ptehsil;
    private javax.swing.JTextField pvillage;
    private javax.swing.JButton update;
    private javax.swing.JPanel wholesaler;
    // End of variables declaration//GEN-END:variables
}
