/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mandioperator;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import vegetabletrading.Mail;
import vegetabletrading.ParabitDB;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HARSHIT
 */
public class MandiDataWS extends javax.swing.JFrame {
    ParabitDB db1;
    int emailotp;
    String postid = null,date,empid;
    Mail vm;
    
    /**
     * Creates new form MandiDataWS
     */
    public MandiDataWS(String a) {
        initComponents();
        empid = a;
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDateTime now = LocalDateTime.now();  
        date = (dtf.format(now));
        
        getData();
        
        try
        {                        
            db1 = new ParabitDB();
            db1.rs = db1.stm.executeQuery("SELECT * FROM `wholesalerreg` WHERE MandiCode = '"+ postid +"' ORDER BY WRID;");            
                      
            //to set date got from data base and set to product table
            while(db1.rs.next())
            {
                String wid = String.valueOf(db1.rs.getInt("WRID"));
                String wname = db1.rs.getString("WRName");
                String wdob = db1.rs.getString("DOB");
                String wregmob = db1.rs.getString("RegMobNo");
                String waltmob = db1.rs.getString("MobNo");
                String wemailid = db1.rs.getString("EmailIDOff");
                String waadhar = db1.rs.getString("AadharNo");
                String wpan = db1.rs.getString("PANNo");
                                         
                DefaultTableModel promodel = (DefaultTableModel)wtable.getModel();
                promodel.addRow(new Object[]{wid,wname,wdob,wregmob,waltmob,wemailid,waadhar,wpan});
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    private void getData(){
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select PostingID from employee where empid = "+empid);
            db1.rs.next();
            postid = db1.rs.getString(1);
                        
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select statename from statecode order by statename");
            
            while(db1.rs.next())
            {
                wsstate.addItem(db1.rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wholesaler = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        wholesalerdef = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        wtable = new javax.swing.JTable();
        wholesalerpanel = new javax.swing.JPanel();
        wtb = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        wsname = new javax.swing.JTextField();
        wsdob = new javax.swing.JTextField();
        wsregmob = new javax.swing.JTextField();
        wsaltmob = new javax.swing.JTextField();
        wsaadhar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        wspan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        wsemail = new javax.swing.JTextField();
        wsphoto = new javax.swing.JLabel();
        wssign = new javax.swing.JLabel();
        wphupload = new javax.swing.JButton();
        wsignupload = new javax.swing.JButton();
        wpnext = new javax.swing.JButton();
        wsid = new javax.swing.JLabel();
        wsotp = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        Verify = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        wshouse = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        wsstreet = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        wscolony = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        wsvillage = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        wsblock = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        wstehsil = new javax.swing.JTextField();
        wspincode = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        wsdistrict = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        wsstate = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        wanext = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        wsaed = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        wsped = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        wsted = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        wsexp = new javax.swing.JTextField();
        wqnext = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        wsbank = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        wsbranch = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        wsaccno = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        wsifsc = new javax.swing.JTextField();
        wupdate = new javax.swing.JButton();
        empwid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wholesaler.setBackground(new java.awt.Color(255, 255, 255));
        wholesaler.setMinimumSize(new java.awt.Dimension(1170, 478));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("   Wholesaler Details ");

        wholesalerdef.setBackground(new java.awt.Color(255, 255, 255));
        wholesalerdef.setMaximumSize(new java.awt.Dimension(1154, 391));
        wholesalerdef.setMinimumSize(new java.awt.Dimension(1154, 391));

        wtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "DOB", "Reg Mob No", "Alt Mob No", "Email ID", "Aadhar", "PAN No"
            }
        ));
        jScrollPane2.setViewportView(wtable);

        javax.swing.GroupLayout wholesalerdefLayout = new javax.swing.GroupLayout(wholesalerdef);
        wholesalerdef.setLayout(wholesalerdefLayout);
        wholesalerdefLayout.setHorizontalGroup(
            wholesalerdefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1159, Short.MAX_VALUE)
            .addGroup(wholesalerdefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wholesalerdefLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        wholesalerdefLayout.setVerticalGroup(
            wholesalerdefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
            .addGroup(wholesalerdefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wholesalerdefLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        wholesalerpanel.setBackground(new java.awt.Color(204, 255, 204));
        wholesalerpanel.setMaximumSize(new java.awt.Dimension(1154, 391));
        wholesalerpanel.setMinimumSize(new java.awt.Dimension(1154, 391));

        wtb.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Alt Mob No.");

        jLabel5.setText("Reg Mob No.");

        jLabel6.setText("DOB");

        jLabel7.setText("Name");

        jLabel8.setText("Wholesaler ID :");

        jLabel9.setText("Aadhar No.");

        jLabel10.setText("Pan No.");

        jLabel11.setText("Email ID");

        wsphoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        wsphoto.setText("           Photo");
        wsphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        wsphoto.setPreferredSize(new java.awt.Dimension(134, 172));
        wsphoto.setVerifyInputWhenFocusTarget(false);

        wssign.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        wssign.setText("           Signature");
        wssign.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        wssign.setPreferredSize(new java.awt.Dimension(151, 50));
        wssign.setVerifyInputWhenFocusTarget(false);

        wphupload.setText("Upload");
        wphupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wphuploadActionPerformed(evt);
            }
        });

        wsignupload.setText("Upload");
        wsignupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wsignuploadActionPerformed(evt);
            }
        });

        wpnext.setText("Next");
        wpnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpnextActionPerformed(evt);
            }
        });

        jLabel61.setText("Otp :");

        Verify.setText("Verify");
        Verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyActionPerformed(evt);
            }
        });

        jButton7.setText("Send OTP");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wsname, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(wsdob)
                    .addComponent(wsregmob)
                    .addComponent(wsaltmob)
                    .addComponent(wsid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wsaadhar)
                    .addComponent(wspan)
                    .addComponent(wsemail, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(wsotp))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(wsphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(wssign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(wsignupload)
                                .addGap(72, 72, 72))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Verify, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(63, 63, 63)
                                .addComponent(wphupload)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wpnext)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(wsid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(wsname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(wsaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(wsdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(wspan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(wsregmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(wsemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(wsaltmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61)
                            .addComponent(wsotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Verify)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(wsphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(wssign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(wsignupload)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wphupload)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(wpnext)
                .addGap(40, 40, 40))
        );

        wtb.addTab("Personal Details", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("House No.");

        jLabel16.setText("Street");

        jLabel14.setText("Colony");

        jLabel13.setText("City/Village");

        jLabel17.setText("Block");

        wsblock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wsblockActionPerformed(evt);
            }
        });

        jLabel15.setText("Tehsil");

        jLabel19.setText("PinCode");

        wsdistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose District" }));
        wsdistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wsdistrictActionPerformed(evt);
            }
        });

        jLabel21.setText("District");

        wsstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose State" }));
        wsstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wsstateActionPerformed(evt);
            }
        });

        jLabel18.setText("State");

        wanext.setText("Next");
        wanext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wanextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wanext)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wsstate, 0, 150, Short.MAX_VALUE)
                            .addComponent(wshouse)
                            .addComponent(wsvillage))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wsdistrict, 0, 150, Short.MAX_VALUE)
                            .addComponent(wsstreet)
                            .addComponent(wsblock))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wscolony, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(wstehsil)
                            .addComponent(wspincode))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(wshouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wsstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wscolony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wsvillage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(wsblock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(wstehsil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(wsstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(wsdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(wspincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(wanext)
                .addGap(47, 47, 47))
        );

        wtb.addTab("Address", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setText("Acadmic Qualification");

        wsaed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Academic Qualification", "10th", "12th", " " }));

        jLabel29.setText("Profesional Qualifcation");

        jLabel27.setText("Technical Qualification");

        jLabel28.setText("Experience");

        wqnext.setText("Next");
        wqnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wqnextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wsted, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wsaed, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wsped)
                    .addComponent(wsexp, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(306, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wqnext)
                .addGap(81, 81, 81))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29)
                    .addComponent(wsped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wsaed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wsexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(wsted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(wqnext)
                .addGap(63, 63, 63))
        );

        wtb.addTab("Qualificaton", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setText("Bank Name");

        wsbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wsbankActionPerformed(evt);
            }
        });

        jLabel24.setText("Branch Name");

        jLabel25.setText("Account No.");

        jLabel36.setText("IFSC Code");

        wupdate.setText("Update");
        wupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wsaccno, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wsbank, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wsbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wsifsc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(403, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wupdate)
                .addGap(58, 58, 58))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(wsbank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wsbranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(wsaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(wsifsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(wupdate)
                .addGap(57, 57, 57))
        );

        wtb.addTab("Bank Details", jPanel5);

        javax.swing.GroupLayout wholesalerpanelLayout = new javax.swing.GroupLayout(wholesalerpanel);
        wholesalerpanel.setLayout(wholesalerpanelLayout);
        wholesalerpanelLayout.setHorizontalGroup(
            wholesalerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wtb)
        );
        wholesalerpanelLayout.setVerticalGroup(
            wholesalerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wtb, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        jLayeredPane2.setLayer(wholesalerdef, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(wholesalerpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(wholesalerdef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addComponent(wholesalerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholesalerdef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(wholesalerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Wholesaler ID");

        jButton5.setText("Get");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel37.setText(" MANDI DATA");
        jLabel37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wholesalerLayout = new javax.swing.GroupLayout(wholesaler);
        wholesaler.setLayout(wholesalerLayout);
        wholesalerLayout.setHorizontalGroup(
            wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholesalerLayout.createSequentialGroup()
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(empwid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton5))
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addGap(497, 497, 497)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wholesalerLayout.createSequentialGroup()
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(wholesalerLayout.createSequentialGroup()
                        .addGap(508, 508, 508)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(21, 21, 21))
        );
        wholesalerLayout.setVerticalGroup(
            wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wholesalerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(wholesalerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empwid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholesaler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wholesaler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wphuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wphuploadActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String wpathimg = f.getAbsolutePath();

        try {
            BufferedImage bi = ImageIO.read(new File(wpathimg));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            wsphoto.setIcon(icon);

            // TODO add your handling code here:
        } catch (Exception e) {
            System.out.println(e);
        }

        String query = "UPDATE `wholesalerreg` SET WRphoto = ?";
        db1 = new ParabitDB();
        try {
            db1.pst = db1.con.prepareStatement(query);

            InputStream img = new FileInputStream(wpathimg);

            db1.pst.setBlob(1, img);

            db1.pst.executeUpdate();

            // TODO add your handling code here:
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_wphuploadActionPerformed

    private void wsignuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wsignuploadActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String wpathsign = f.getAbsolutePath();
        
        try {
            BufferedImage bi = ImageIO.read(new File(wpathsign));
            Image im = bi.getScaledInstance(151, 50, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(im);
            wssign.setIcon(icon);

            // TODO add your handling code here:
        } catch (Exception e) {
            System.out.println(e);
        }

        String query = "UPDATE `wholesalerreg` SET Signature = ?";
        db1 = new ParabitDB();
        try {
            db1.pst = db1.con.prepareStatement(query);

            InputStream sign = new FileInputStream(wpathsign);

            db1.pst.setBlob(1, sign);

            db1.pst.executeUpdate();

            // TODO add your handling code here:
        } catch (Exception e) {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_wsignuploadActionPerformed

    private void wpnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpnextActionPerformed

        String s1,s2,s3,s4,s5,s6,s7,s8,wid;

        wid = wsid.getText();
        s2 = wsname.getText();
        s3 = wsdob.getText();
        s4 = wsregmob.getText();
        s5 = wsaltmob.getText();
        s6 = wsaadhar.getText();
        s7 = wspan.getText();
        s8 = wsemail.getText();
        //s9 = "hi";

        String sql = "UPDATE `wholesalerreg` SET WRName ='"+s2+"', DOB ='"+s3+"', RegMobNo ='"+s4+"', MobNo ='"+s5+"', AadharNo ='"+s6+"', PANNo ='"+s7+"', EmailIdOff ='"+s8+"', UpdationDate ='"+date+"' where WRID = " + wid;
        //System.out.println(sql);

        db1 = new ParabitDB();
        try
        {
            db1.stm.executeUpdate(sql);

        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }

        int i = wtb.getSelectedIndex();
        wtb.setSelectedIndex(i+1);
        // TODO add your handling code here:
    }//GEN-LAST:event_wpnextActionPerformed

    private void VerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyActionPerformed

        int otpval = Integer.parseInt(wsotp.getText());
        try
        {
            if(otpval==emailotp){
                JOptionPane.showMessageDialog(null,"OTP Verified...");
                
                wsname.setEditable(true);
                wsdob.setEditable(true);
                wsregmob.setEditable(true);
                wsaltmob.setEditable(true);
                wsemail.setEditable(true);
                wsaadhar.setEditable(true);
                wspan.setEditable(true);
                wshouse.setEditable(true);
                wsstreet.setEditable(true);
                wscolony.setEditable(true);
                wsvillage.setEditable(true);
                wsblock.setEditable(true);
                wstehsil.setEditable(true);
                wsstate.setEditable(true);
                wsdistrict.setEditable(true);
                wspincode.setEditable(true);
                wsaed.setEditable(true);
                wsped.setEditable(true);
                wsexp.setEditable(true);
                wsted.setEditable(true);
                wsbank.setEditable(true);
                wsbranch.setEditable(true);
                wsaccno.setEditable(true);
                wsifsc.setEditable(true);
            
                wpnext.setVisible(true);
                wanext.setVisible(true);
                wqnext.setVisible(true);
                wupdate.setVisible(true);
                wphupload.setVisible(true);
                wsignupload.setVisible(true);
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Valid OTP!!!");
            }

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_VerifyActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String email = wsemail.getText();

        if(email!= "null")
        {
            vm = new Mail(email);
            emailotp = vm.oneTimePass();
            System.out.println(emailotp);
        }
        else{
            JOptionPane.showMessageDialog(this,"Enter valid email...");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void wsblockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wsblockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wsblockActionPerformed

    private void wsdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wsdistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wsdistrictActionPerformed

    private void wsstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wsstateActionPerformed

        String state = wsstate.getSelectedItem().toString();

        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select distinct distname from districtcode where statecode = (select statecode from statecode where statename = '" + state + "') order by distname");

            while(db1.rs.next())
            {
                wsdistrict.addItem(db1.rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_wsstateActionPerformed

    private void wanextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wanextActionPerformed

        String s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,wid;

        wid = wsid.getText();
        s1 = wshouse.getText();
        s2 = wsstreet.getText();
        s3 = wscolony.getText();
        s4 = wsvillage.getText();
        s5 = wsblock.getText();
        s6 = wstehsil.getText();
        s7 = (String)wsstate.getSelectedItem();
        s8 = (String)wsdistrict.getSelectedItem();
        s9 = wspincode.getText();
        
        String sql = "UPDATE wholesalerreg SET HouseNo ='"+s1+"', Street ='"+s2+"', Colony ='"+s3+"', CityVillage ='"+s4+"', Block ='"+s5+"', Tehsil ='"+s6+"', State ='"+s7+"', Dist ='"+s8+"', Pincode ='"+s9+"', UpdationDate ='"+date+"' where WRID = " + wid;
        //System.out.println(sql);

        db1 = new ParabitDB();
        try
        {
            db1.stm.executeUpdate(sql);

        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }

        int i = wtb.getSelectedIndex();
        wtb.setSelectedIndex(i+1);
        // TODO add your handling code here:
    }//GEN-LAST:event_wanextActionPerformed

    private void wqnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wqnextActionPerformed

        String s1,s2,s3,s4,wid;

        wid = wsid.getText();
        s1 = (String)wsaed.getSelectedItem();
        s2 = wsted.getText();
        s3 = wsped.getText();
        s4 = wsexp.getText();

        String iqs = "UPDATE wholesalerreg SET WRAEdu ='"+s1+"', WRTEdu ='"+s2+"', WRPEdu ='"+s3+"', WRExp ='"+s4+"', UpdationDate ='"+date+"' where WRID = " + wid;
        //System.out.println(iqs);

        // To insert values of this tab in database
        db1 = new ParabitDB();
        try
        {
            db1.stm.executeUpdate(iqs);

        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }

        int i = wtb.getSelectedIndex();
        wtb.setSelectedIndex(i+1);
        // TODO add your handling code here:
    }//GEN-LAST:event_wqnextActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String wrid = empwid.getText();
        try
        {
            String sql = ("SELECT * FROM `wholesalerreg` WHERE WRID = '"+ wrid +"' and MandiCode = '"+ postid +"';");
            //db1 = new ParabitDB();
            //db1.rs = db1.stm.executeQuery(sql);
            db1 = new ParabitDB();
            db1.rs = db1.stm.executeQuery(sql);
            boolean check = db1.rs.next();
            if(check)
            {
                //to set date got from database for pannel
                //while(db1.rs.next())
                String wid = null,wname =null,wdob = null,wregmob = null,waltmob = null,wemailid = null,waadhar = null,wpan = null,whouse = null,wstreet =null,wcolony = null,wcity = null,wblock = null,wtehsil = null,wdist = null,wstate = null,wpincode = null,wlandsize = null,wirr = null,waed = null,wped = null,wted = null,wexp = null,wbank = null,wbranch = null,waccno = null,wifsc = null;
       
                wid = String.valueOf(db1.rs.getInt("WRID"));
                wname = db1.rs.getString("WRName");
                waadhar = db1.rs.getString("AadharNo");
                wpan = db1.rs.getString("PANNo");
                wdob = db1.rs.getString("DOB");
                wregmob = db1.rs.getString("RegMobNo");
                waltmob = db1.rs.getString("MobNo");
                wemailid = db1.rs.getString("EmailIDOff");
                BufferedImage pbi = ImageIO.read(db1.rs.getBinaryStream("WRPhoto"));
                Image pimg = pbi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
                BufferedImage sbi = ImageIO.read(db1.rs.getBinaryStream("Signature"));
                Image simg = sbi.getScaledInstance(151, 50, Image.SCALE_SMOOTH );
                waccno = db1.rs.getString("BAccNo");
                wbank = db1.rs.getString("BName");
                wifsc = db1.rs.getString("BIFSC");
                wbranch = db1.rs.getString("BBranch");
                waed = db1.rs.getString("WRAEdu");
                wped = db1.rs.getString("WRPEdu");
                wted = db1.rs.getString("WRTEdu");
                wexp = db1.rs.getString("WRExp");
                whouse = db1.rs.getString("HouseNo");
                wstreet = db1.rs.getString("Street");
                wcolony = db1.rs.getString("Colony");
                wcity = db1.rs.getString("CityVillage");
                wblock = db1.rs.getString("Block");
                wtehsil = db1.rs.getString("Tehsil");
                wdist = db1.rs.getString("Dist");
                wstate = db1.rs.getString("State");
                wpincode = db1.rs.getString("Pincode");
                
                wsid.setText(wid);
                wsname.setText(wname);
                wsdob.setText(wdob);
                wsregmob.setText(wregmob);
                wsaltmob.setText(waltmob);
                wsemail.setText(wemailid);
                wsaadhar.setText(waadhar);
                wspan.setText(wpan);
                wsphoto.setIcon(new ImageIcon(pimg));
                wssign.setIcon(new ImageIcon(simg));
                wshouse.setText(whouse);
                wsstreet.setText(wstreet);
                wscolony.setText(wcolony);
                wsvillage.setText(wcity);
                wsblock.setText(wblock);
                wstehsil.setText(wtehsil);
                wsstate.setSelectedItem(wstate);
                wsdistrict.setSelectedItem(wdist);
                wspincode.setText(wpincode);
                wsaed.setSelectedItem(waed);
                wsped.setText(wped);
                wsexp.setText(wexp);
                wsted.setText(wted);
                wsbank.setText(wbank);
                wsbranch.setText(wbranch);
                wsaccno.setText(waccno);
                wsifsc.setText(wifsc);
                
                wholesalerdef.setVisible(false);
                wholesalerpanel.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "WholeSaler Id "+wrid+" not found...");
                wholesalerdef.setVisible(true);
                wholesalerpanel.setVisible(false);
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        wsname.setEditable(false);
        wsdob.setEditable(false);
        wsregmob.setEditable(false);
        wsaltmob.setEditable(false);
        wsemail.setEditable(false);
        wsaadhar.setEditable(false);
        wspan.setEditable(false);
        wshouse.setEditable(false);
        wsstreet.setEditable(false);
        wscolony.setEditable(false);
        wsvillage.setEditable(false);
        wsblock.setEditable(false);
        wstehsil.setEditable(false);
        wsstate.setEditable(false);
        wsdistrict.setEditable(false);
        wspincode.setEditable(false);
        wsaed.setEditable(false);
        wsped.setEditable(false);
        wsexp.setEditable(false);
        wsted.setEditable(false);
        wsbank.setEditable(false);
        wsbranch.setEditable(false);
        wsaccno.setEditable(false);
        wsifsc.setEditable(false);
        
        wpnext.setVisible(false);
        wanext.setVisible(false);
        wqnext.setVisible(false);
        wupdate.setVisible(false);
        wphupload.setVisible(false);
        wsignupload.setVisible(false);
        
        wtb.setSelectedIndex(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void wsbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wsbankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wsbankActionPerformed

    private void wupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wupdateActionPerformed

        String s1,s2,s3,s4,wid;

        wid = wsid.getText();
        s1 = wsbank.getText();
        s2 = wsaccno.getText();
        s3 = wsifsc.getText();
        s4 = wsbranch.getText();
               
        String query = "UPDATE wholesalerreg SET BName ='"+s1+"', BAccNo ='"+s2+"', BIFSC ='"+s3+"', BBranch ='"+s4+"', UpdationDate ='"+date+"' where WRID = " + wid;
        //System.out.println(ibs);
                
        // To insert values of this tab in database
        db1 = new ParabitDB();
        try
        {
            db1.stm.executeUpdate(query);
            JOptionPane.showMessageDialog(this,"Updated Sucessfully...");

        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_wupdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        wholesalerpanel.setVisible(false);
        empwid.setText("");
        wholesalerdef.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MandiDataWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MandiDataWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MandiDataWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MandiDataWS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                new MandiDataWS(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Verify;
    private javax.swing.JTextField empwid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton wanext;
    private javax.swing.JPanel wholesaler;
    private javax.swing.JPanel wholesalerdef;
    private javax.swing.JPanel wholesalerpanel;
    private javax.swing.JButton wphupload;
    private javax.swing.JButton wpnext;
    private javax.swing.JButton wqnext;
    private javax.swing.JTextField wsaadhar;
    private javax.swing.JTextField wsaccno;
    private javax.swing.JComboBox<String> wsaed;
    private javax.swing.JTextField wsaltmob;
    private javax.swing.JTextField wsbank;
    private javax.swing.JTextField wsblock;
    private javax.swing.JTextField wsbranch;
    private javax.swing.JTextField wscolony;
    private javax.swing.JComboBox<String> wsdistrict;
    private javax.swing.JTextField wsdob;
    private javax.swing.JTextField wsemail;
    private javax.swing.JTextField wsexp;
    private javax.swing.JTextField wshouse;
    private javax.swing.JLabel wsid;
    private javax.swing.JTextField wsifsc;
    private javax.swing.JButton wsignupload;
    private javax.swing.JTextField wsname;
    private javax.swing.JTextField wsotp;
    private javax.swing.JTextField wspan;
    private javax.swing.JTextField wsped;
    private javax.swing.JLabel wsphoto;
    private javax.swing.JTextField wspincode;
    private javax.swing.JTextField wsregmob;
    private javax.swing.JLabel wssign;
    private javax.swing.JComboBox<String> wsstate;
    private javax.swing.JTextField wsstreet;
    private javax.swing.JTextField wsted;
    private javax.swing.JTextField wstehsil;
    private javax.swing.JTextField wsvillage;
    private javax.swing.JTable wtable;
    private javax.swing.JTabbedPane wtb;
    private javax.swing.JButton wupdate;
    // End of variables declaration//GEN-END:variables
}
