/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package panchayatoperator;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import vegetabletrading.FaceCapture;
import vegetabletrading.FaceDetection;
import vegetabletrading.ParabitDB;
import vegetabletrading.Mail;

/**
 *
 * @author harshit
 */
public class FarmerReg extends javax.swing.JDialog {
    ParabitDB db1;
    ParabitDB db2;
    ParabitDB db3;
    ParabitDB db4;
    FaceDetection fd;
    FaceCapture fc;
    Mail vm;
    
    int fid = 0,emailotp;
    String state, aadhar, pathimg, pathsign,id,pcode,email;
    
    /**
     * Creates new form FarmerReg
     */
    public FarmerReg(java.awt.Frame parent, boolean modal, String a, String b) {
        super(parent, modal);
        initComponents();
        id = a;
        pcode = b;
        
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select statename from statecode order by statename");
            
            while(db1.rs.next())
            {
                farstate.addItem(db1.rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        personalsave.setVisible(false);
               
    }
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        smartphoneBtGrp = new javax.swing.ButtonGroup();
        compBtGrp = new javax.swing.ButtonGroup();
        tb1 = new javax.swing.JTabbedPane();
        personaltab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        farname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        faraadhar = new javax.swing.JTextField();
        farregmob = new javax.swing.JTextField();
        farmob2 = new javax.swing.JTextField();
        faremail = new javax.swing.JTextField();
        farpan = new javax.swing.JTextField();
        personalsave = new javax.swing.JButton();
        fardobmonth = new com.toedter.calendar.JMonthChooser();
        fardobyear = new com.toedter.calendar.JYearChooser();
        farphupload = new javax.swing.JButton();
        fardobdate = new javax.swing.JComboBox<>();
        farphoto = new javax.swing.JLabel();
        farsign = new javax.swing.JLabel();
        farsignupload = new javax.swing.JButton();
        farpfid = new javax.swing.JLabel();
        otp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Verify = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        addresstab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        farhouse = new javax.swing.JTextField();
        farvillage = new javax.swing.JTextField();
        farstreet = new javax.swing.JTextField();
        farlandsize = new javax.swing.JTextField();
        farblock = new javax.swing.JTextField();
        farcolony = new javax.swing.JTextField();
        farpincode = new javax.swing.JTextField();
        fartehsil = new javax.swing.JTextField();
        farstate = new javax.swing.JComboBox<>();
        fardistrict = new javax.swing.JComboBox<>();
        farirr = new javax.swing.JComboBox<>();
        addsave = new javax.swing.JButton();
        farafid = new javax.swing.JLabel();
        qualitab = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        farped = new javax.swing.JTextField();
        farted = new javax.swing.JTextField();
        farexp = new javax.swing.JTextField();
        faraed = new javax.swing.JComboBox<>();
        qualsave = new javax.swing.JButton();
        farqfid = new javax.swing.JLabel();
        banktab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        farbank = new javax.swing.JTextField();
        farifsc = new javax.swing.JTextField();
        faraccno = new javax.swing.JTextField();
        farbranch = new javax.swing.JTextField();
        farkcc = new javax.swing.JTextField();
        banksave = new javax.swing.JButton();
        farbfid = new javax.swing.JLabel();
        addinfotab = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        fartrans = new javax.swing.JComboBox<>();
        farscap = new javax.swing.JTextField();
        farscapcold = new javax.swing.JTextField();
        farsphoneyes = new javax.swing.JRadioButton();
        farsphoneno = new javax.swing.JRadioButton();
        farcompno = new javax.swing.JRadioButton();
        farcompyes = new javax.swing.JRadioButton();
        farnote = new javax.swing.JTextField();
        addinfonext = new javax.swing.JButton();
        faraifid = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Farmer Registration");

        jLabel5.setText("Name");

        jLabel1.setText("DOB");

        jLabel6.setText("Aadhar No.");

        jLabel7.setText("Reg Mobile No.");

        jLabel8.setText("Email ID");

        jLabel9.setText("PAN No.");

        jLabel10.setText("Altenate Mobile No.");

        faremail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faremailActionPerformed(evt);
            }
        });

        personalsave.setText("Save And Next");
        personalsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalsaveActionPerformed(evt);
            }
        });

        farphupload.setText("Upload");
        farphupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farphuploadActionPerformed(evt);
            }
        });

        fardobdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        farphoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        farphoto.setText("           Photo");
        farphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        farphoto.setPreferredSize(new java.awt.Dimension(134, 172));
        farphoto.setVerifyInputWhenFocusTarget(false);

        farsign.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        farsign.setText("           Signature");
        farsign.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        farsign.setPreferredSize(new java.awt.Dimension(151, 50));
        farsign.setVerifyInputWhenFocusTarget(false);

        farsignupload.setText("Upload");
        farsignupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farsignuploadActionPerformed(evt);
            }
        });

        farpfid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton1.setText("Send OTP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Verify.setText("Verify");
        Verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyActionPerformed(evt);
            }
        });

        jLabel36.setText("Otp :");

        jButton2.setText("Capture Live");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personaltabLayout = new javax.swing.GroupLayout(personaltab);
        personaltab.setLayout(personaltabLayout);
        personaltabLayout.setHorizontalGroup(
            personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaltabLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personaltabLayout.createSequentialGroup()
                        .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personaltabLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(farpfid, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personaltabLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(farname, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personaltabLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(fardobdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fardobmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fardobyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personaltabLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(farregmob, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personaltabLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(farphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(farsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(personaltabLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(farsignupload))))
                            .addGroup(personaltabLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(farphupload)
                                .addGap(33, 33, 33)
                                .addComponent(jButton2))))
                    .addGroup(personaltabLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(farpan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personaltabLayout.createSequentialGroup()
                        .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personaltabLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(farmob2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personaltabLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(faraadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(faremail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(otp))
                        .addGap(30, 30, 30)
                        .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(Verify, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personaltabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(personalsave)
                .addGap(40, 40, 40))
        );
        personaltabLayout.setVerticalGroup(
            personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaltabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personaltabLayout.createSequentialGroup()
                        .addComponent(farpfid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(farname)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personaltabLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel1))
                            .addComponent(fardobdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fardobmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fardobyear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personaltabLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7))
                            .addComponent(farregmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personaltabLayout.createSequentialGroup()
                        .addComponent(farphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(farphupload)
                            .addComponent(jButton2)))
                    .addGroup(personaltabLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(farsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(farsignupload)))
                .addGap(27, 27, 27)
                .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(farmob2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(faremail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(personaltabLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))))
                .addGap(34, 34, 34)
                .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personaltabLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(faraadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel36)
                        .addComponent(otp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Verify)))
                .addGap(35, 35, 35)
                .addGroup(personaltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personaltabLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(farpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(personalsave)
                .addGap(44, 44, 44))
        );

        tb1.addTab("Personal Details", personaltab);

        jLabel2.setText("House No.");

        jLabel3.setText("City/Village");

        jLabel12.setText("State");

        jLabel13.setText("Land Size (Acre)");

        jLabel14.setText("Colony");

        jLabel15.setText("Tehsil");

        jLabel16.setText("Street");

        jLabel17.setText("Block");

        jLabel19.setText("PinCode");

        jLabel20.setText("Irrigation Mode");

        jLabel21.setText("District");

        farblock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farblockActionPerformed(evt);
            }
        });

        farstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose State" }));
        farstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farstateActionPerformed(evt);
            }
        });

        fardistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose District" }));
        fardistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fardistrictActionPerformed(evt);
            }
        });

        farirr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Irrigation Mode", "Tube Well", "River", "Canal", "Well", "Other" }));

        addsave.setText("Save And Next");
        addsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsaveActionPerformed(evt);
            }
        });

        farafid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        farafid.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                farafidInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout addresstabLayout = new javax.swing.GroupLayout(addresstab);
        addresstab.setLayout(addresstabLayout);
        addresstabLayout.setHorizontalGroup(
            addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addresstabLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(farstate, javax.swing.GroupLayout.Alignment.LEADING, 0, 146, Short.MAX_VALUE)
                    .addComponent(farvillage, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(farhouse, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(farlandsize))
                .addGap(50, 50, 50)
                .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addresstabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addsave)
                        .addGap(130, 130, 130))
                    .addGroup(addresstabLayout.createSequentialGroup()
                        .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(addresstabLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel18)))
                        .addGap(30, 30, 30)
                        .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(farstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(farblock, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(farirr, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fardistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(farcolony, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(farpincode, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fartehsil, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
            .addGroup(addresstabLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(farafid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addresstabLayout.setVerticalGroup(
            addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addresstabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(farafid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(farhouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farcolony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(farblock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(fartehsil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farvillage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addresstabLayout.createSequentialGroup()
                        .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(farstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)
                                .addComponent(fardistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(farpincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(addresstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(farlandsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(farirr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel18))
                .addGap(45, 45, 45)
                .addComponent(addsave)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        tb1.addTab("Address", addresstab);

        jLabel26.setText("Acadmic Qualification");

        jLabel27.setText("Technical Qualification");

        jLabel28.setText("Experience");

        jLabel29.setText("Profesional Qualifcation");

        faraed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Academic Qualification", "10th", "12th", " " }));

        qualsave.setText("Save And Next");
        qualsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualsaveActionPerformed(evt);
            }
        });

        farqfid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout qualitabLayout = new javax.swing.GroupLayout(qualitab);
        qualitab.setLayout(qualitabLayout);
        qualitabLayout.setHorizontalGroup(
            qualitabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qualitabLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(qualitabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(qualitabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(farted, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faraed, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(qualitabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qualsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(qualitabLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(qualitabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(qualitabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(farped, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(farexp))))
                .addGap(216, 216, 216))
            .addGroup(qualitabLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(farqfid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qualitabLayout.setVerticalGroup(
            qualitabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qualitabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(farqfid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(qualitabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29)
                    .addComponent(farped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faraed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(qualitabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(farexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(farted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(45, 45, 45)
                .addComponent(qualsave)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        tb1.addTab("Qualificaton", qualitab);

        jLabel4.setText("Bank Name");

        jLabel22.setText("Account No.");

        jLabel23.setText("IFSC Code");

        jLabel24.setText("Branch Name");

        jLabel25.setText("Kisan Credit  Card");

        banksave.setText("Save And Next");
        banksave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banksaveActionPerformed(evt);
            }
        });

        farbfid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout banktabLayout = new javax.swing.GroupLayout(banktab);
        banktab.setLayout(banktabLayout);
        banktabLayout.setHorizontalGroup(
            banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(banktabLayout.createSequentialGroup()
                .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(banktabLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(banksave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, banktabLayout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(faraccno, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(farbank, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(farifsc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(37, 37, 37)
                            .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(farbranch, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(farkcc))
                            .addGap(22, 22, 22)))
                    .addGroup(banktabLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(farbfid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        banktabLayout.setVerticalGroup(
            banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(banktabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(farbfid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel24)
                    .addComponent(farbank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farbranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(faraccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(farkcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(banktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(farifsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(banksave)
                .addGap(227, 227, 227))
        );

        tb1.addTab("Bank Details", banktab);

        jLabel30.setText("Transport");

        jLabel31.setText("Storage Capacity");

        jLabel32.setText("Cold Storage Capacity");

        jLabel33.setText("SmartPhone");

        jLabel34.setText("Computer");

        jLabel35.setText("Note");

        fartrans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Transport Mode", "Truck", "Mini Truck", "Pickup", "Loading Auto", "Tractor with Trolly", " " }));

        smartphoneBtGrp.add(farsphoneyes);
        farsphoneyes.setText("Yes");

        smartphoneBtGrp.add(farsphoneno);
        farsphoneno.setText("No");

        compBtGrp.add(farcompno);
        farcompno.setText("No");

        compBtGrp.add(farcompyes);
        farcompyes.setText("Yes");

        farnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farnoteActionPerformed(evt);
            }
        });

        addinfonext.setText("Submit");
        addinfonext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addinfonextActionPerformed(evt);
            }
        });

        faraifid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout addinfotabLayout = new javax.swing.GroupLayout(addinfotab);
        addinfotab.setLayout(addinfotabLayout);
        addinfotabLayout.setHorizontalGroup(
            addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addinfotabLayout.createSequentialGroup()
                .addGroup(addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addinfotabLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fartrans, 0, 189, Short.MAX_VALUE)
                            .addComponent(farscap)
                            .addComponent(farscapcold)
                            .addComponent(farnote))
                        .addGap(50, 50, 50)
                        .addGroup(addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(farsphoneyes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(farcompyes, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(farcompno, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(farsphoneno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(addinfotabLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(faraifid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addinfotabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addinfonext)
                .addGap(305, 305, 305))
        );
        addinfotabLayout.setVerticalGroup(
            addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addinfotabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(faraifid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(fartrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(farsphoneyes)
                    .addComponent(farsphoneno))
                .addGap(40, 40, 40)
                .addGroup(addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(farscap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(farcompyes)
                    .addComponent(farcompno))
                .addGap(40, 40, 40)
                .addGroup(addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(farscapcold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(addinfotabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(farnote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(addinfonext)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        tb1.addTab("Additonal Information", addinfotab);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel11.setText("  FARMER REGISTRATION");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void faremailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faremailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faremailActionPerformed

    private void farnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farnoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_farnoteActionPerformed
            
    private void addinfonextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addinfonextActionPerformed

        String s1,s2,s3,s4,s5,s6,s7,sp ="",comp="";
        s1 = (String)fartrans.getSelectedItem();
        s2 = farscap.getText();
        s3 = farscapcold.getText();
        s4 = farnote.getText();
        if(farsphoneyes.isSelected())
        {
            sp = "Y";
        }
        if(farsphoneno.isSelected())
        {
            sp = "N";
        }
        s5 = sp ;
        if(farcompyes.isSelected())
        {
            comp = "Y";
        }
        if(farcompno.isSelected())
        {
            comp = "N";
        }
        s6 = comp;
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDateTime now = LocalDateTime.now();  
        s7 = (dtf.format(now));
        
        String iais = "UPDATE farmerreg SET TVehical ='"+s1+"', SCap ='"+s2+"', SCapCold ='"+s3+"', Note ='"+s4+"', SmartPhone ='"+s5+"', Comp ='"+s6+"', RegDate ='"+s7+"', POID ='"+id+"', PCode ='"+pcode+"' where AadharNo = '" + aadhar +"'";
        System.out.println(iais);
        
        // To insert values of this tab in database
        db3 = new ParabitDB();
        try
        {
            db3.stm.executeUpdate(iais);
                        
            new Mail(email,farname.getText());
            JOptionPane.showMessageDialog(this,"Registered Successfully!!!");
            this.setVisible(false);
        
        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_addinfonextActionPerformed

    private void farblockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farblockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_farblockActionPerformed

    private void farphuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farphuploadActionPerformed
        String path = null;
       
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path = f.getAbsolutePath();
        pathimg = path;
        System.out.println(path);
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            farphoto.setIcon(icon);
            
                // TODO add your handling code here:
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_farphuploadActionPerformed

    private void farstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farstateActionPerformed
        state = farstate.getSelectedItem().toString();
        System.out.println(state);
        
        db2 = new ParabitDB();
        try
        {
            fardistrict.removeAllItems();
            fardistrict.addItem("Select District");
            db2.rs = db2.stm.executeQuery("select distinct distname from districtcode where statecode = (select statecode from statecode where statename = '" + state + "') order by distname");
            while(db2.rs.next())
            {
                fardistrict.addItem(db2.rs.getString(1));  
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_farstateActionPerformed

    private void fardistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fardistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fardistrictActionPerformed

    private void personalsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalsaveActionPerformed
        
        String date = (String)fardobdate.getSelectedItem();
        int month=fardobmonth.getMonth()+1;
        int year=fardobyear.getYear();
        
                       
        String s1,s2,s3,s4,s6,s7,s8,s9;
        
        s1 = farname.getText();
        s2 = year+"-"+month+"-"+date;
        s3 = farregmob.getText();
        s4 = farmob2.getText();
        aadhar = faraadhar.getText();
        //s6 = "hi";
        s7 = faremail.getText();
        s8 = farpan.getText();
        //s9 = "hi";
        
        String ips = "insert into farmerreg (FName, DOB, RegMobNo, MobNo, AadharNo, Fphoto, EmailIdOff, Signature, PANNo) values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+aadhar+"',?,'"+s7+"',?,'"+s8+"')";
        System.out.println(ips);
        
        db2 = new ParabitDB();
        try
        {
            db2.rs = db2.stm.executeQuery("SELECT * FROM `farmerreg` WHERE AadharNo = '"+ aadhar +"'");
            boolean check = db2.rs.next();
            if(check){
                JOptionPane.showMessageDialog(this,"Already registered...");
                this.setVisible(false);
            }else{
                db3 = new ParabitDB();
                db3.pst = db3.con.prepareStatement(ips);
            
                InputStream img = new FileInputStream(pathimg);
                InputStream sign = new FileInputStream(pathsign);             
          
                db3.pst.setBlob(1, img);
                db3.pst.setBlob(2, sign);         
   
                db3.pst.executeUpdate();
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }
                
        // To get value of fid from database
        db4 = new ParabitDB();
        try
        {
            db4.rs = db4.stm.executeQuery("select FID from farmerreg where aadharNo = "+ aadhar);
           
              db4.rs.next();
              fid = db4.rs.getInt(1);
                  
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        farpfid.setText("Farmer Id : "+fid);
        farafid.setText("Farmer Id : "+fid);
        farqfid.setText("Farmer Id : "+fid);
        farbfid.setText("Farmer Id : "+fid);
        faraifid.setText("Farmer Id : "+fid);
        
        
        int i = tb1.getSelectedIndex();
        tb1.setSelectedIndex(i+1);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_personalsaveActionPerformed

    private void addsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsaveActionPerformed

        String s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11;
      
        s1 = farhouse.getText();
        s2 = farstreet.getText();
        s3 = farcolony.getText();
        s4 = farvillage.getText();
        s5 = farblock.getText();       
        s6 = fartehsil.getText();
        s7 = (String)farstate.getSelectedItem();
        s8 = (String)fardistrict.getSelectedItem();
        s9 = farpincode.getText();
        s10 = farlandsize.getText(); 
        s11 = (String)farirr.getSelectedItem();
        
        String ias = "UPDATE farmerreg SET HouseNo ='"+s1+"', Street ='"+s2+"', Colony ='"+s3+"', CityVillage ='"+s4+"', Block ='"+s5+"', Tehsil ='"+s6+"', State ='"+s7+"', Dist ='"+s8+"', Pincode ='"+s9+"', TotalSize ='"+s10+"', Irrigation ='"+s11+"' where AadharNo = '" + aadhar +"'";
        System.out.println(ias);
        
        // To insert values of this tab in database
        db3 = new ParabitDB();
        try
        {
            db3.stm.executeUpdate(ias);
        
        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }
                
        //To go to next tab
        int i = tb1.getSelectedIndex();
        tb1.setSelectedIndex(i+1);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_addsaveActionPerformed

    private void qualsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualsaveActionPerformed

        String s1,s2,s3,s4;
        s1 = (String)faraed.getSelectedItem();
        s2 = farted.getText();
        s3 = farped.getText();
        s4 = farexp.getText();
        
        String iqs = "UPDATE farmerreg SET FAEdu ='"+s1+"', FTEdu ='"+s2+"', FPEdu ='"+s3+"', FExp ='"+s4+"' where AadharNo = '" + aadhar +"'";
        System.out.println(iqs);
        
        // To insert values of this tab in database
        db3 = new ParabitDB();
        try
        {
            db3.stm.executeUpdate(iqs);
        
        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }
        
        //To go to next tab
        int i = tb1.getSelectedIndex();
        tb1.setSelectedIndex(i+1);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_qualsaveActionPerformed

    private void banksaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banksaveActionPerformed

        String s1,s2,s3,s4,s5;
        s1 = farbank.getText();
        s2 = faraccno.getText();
        s3 = farifsc.getText();
        s4 = farbranch.getText();
        s5 = farkcc.getText();
        
        String ibs = "UPDATE farmerreg SET BName ='"+s1+"', BAccNo ='"+s2+"', BIFSC ='"+s3+"', BBranch ='"+s4+"', KCC ='"+s5+"' where AadharNo = '" + aadhar +"'";
        System.out.println(ibs);
        
        // To insert values of this tab in database
        db3 = new ParabitDB();
        try
        {
            db3.stm.executeUpdate(ibs);
        
        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }
        
        //To go to next tab
        int i = tb1.getSelectedIndex();
        tb1.setSelectedIndex(i+1);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_banksaveActionPerformed

    private void farsignuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farsignuploadActionPerformed

        String path = null;

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path = f.getAbsolutePath();
        pathsign = path;
        
        System.out.println(path);
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image im = bi.getScaledInstance(151, 50, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(im);
            farsign.setIcon(icon);

            // TODO add your handling code here:
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_farsignuploadActionPerformed

    private void farafidInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_farafidInputMethodTextChanged


        // TODO add your handling code here:
    }//GEN-LAST:event_farafidInputMethodTextChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        email = faremail.getText();
        
        if(email!= "null")
        {            
            vm = new Mail(email);
            emailotp = vm.oneTimePass();
            System.out.println(emailotp);
        }
        else{
            JOptionPane.showMessageDialog(this,"Enter valid email...");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyActionPerformed
        
        int otpval = Integer.parseInt(otp.getText());
        try
        {
            if(otpval==emailotp){
                JOptionPane.showMessageDialog(null,"OTP Verified...");
                personalsave.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Valid OTP!!!"); 
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_VerifyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        fd = new FaceDetection();
        fd.start();
        
        JOptionPane.showMessageDialog(null,"Look At the Camera and Press OK");
        
        fc = new FaceCapture(farphoto);
        fd.end = 0;
        //if(fd.end == 0){
         //   StatusUpdate su = new StatusUpdate();
         //   su.start();
        //}
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FarmerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FarmerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FarmerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarmerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                String b = null;
                FarmerReg dialog = new FarmerReg(new javax.swing.JFrame(), true,a,b);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Verify;
    private javax.swing.JButton addinfonext;
    private javax.swing.JPanel addinfotab;
    private javax.swing.JPanel addresstab;
    private javax.swing.JButton addsave;
    private javax.swing.JButton banksave;
    private javax.swing.JPanel banktab;
    private javax.swing.ButtonGroup compBtGrp;
    private javax.swing.JTextField faraadhar;
    private javax.swing.JTextField faraccno;
    private javax.swing.JComboBox<String> faraed;
    private javax.swing.JLabel farafid;
    private javax.swing.JLabel faraifid;
    private javax.swing.JTextField farbank;
    private javax.swing.JLabel farbfid;
    private javax.swing.JTextField farblock;
    private javax.swing.JTextField farbranch;
    private javax.swing.JTextField farcolony;
    private javax.swing.JRadioButton farcompno;
    private javax.swing.JRadioButton farcompyes;
    private javax.swing.JComboBox<String> fardistrict;
    private javax.swing.JComboBox<String> fardobdate;
    private com.toedter.calendar.JMonthChooser fardobmonth;
    private com.toedter.calendar.JYearChooser fardobyear;
    private javax.swing.JTextField faremail;
    private javax.swing.JTextField farexp;
    private javax.swing.JTextField farhouse;
    private javax.swing.JTextField farifsc;
    private javax.swing.JComboBox<String> farirr;
    private javax.swing.JTextField farkcc;
    private javax.swing.JTextField farlandsize;
    private javax.swing.JTextField farmob2;
    private javax.swing.JTextField farname;
    private javax.swing.JTextField farnote;
    private javax.swing.JTextField farpan;
    private javax.swing.JTextField farped;
    private javax.swing.JLabel farpfid;
    private javax.swing.JLabel farphoto;
    private javax.swing.JButton farphupload;
    private javax.swing.JTextField farpincode;
    private javax.swing.JLabel farqfid;
    private javax.swing.JTextField farregmob;
    private javax.swing.JTextField farscap;
    private javax.swing.JTextField farscapcold;
    private javax.swing.JLabel farsign;
    private javax.swing.JButton farsignupload;
    private javax.swing.JRadioButton farsphoneno;
    private javax.swing.JRadioButton farsphoneyes;
    private javax.swing.JComboBox<String> farstate;
    private javax.swing.JTextField farstreet;
    private javax.swing.JTextField farted;
    private javax.swing.JTextField fartehsil;
    private javax.swing.JComboBox<String> fartrans;
    private javax.swing.JTextField farvillage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField otp;
    private javax.swing.JButton personalsave;
    private javax.swing.JPanel personaltab;
    private javax.swing.JPanel qualitab;
    private javax.swing.JButton qualsave;
    private javax.swing.ButtonGroup smartphoneBtGrp;
    private javax.swing.JTabbedPane tb1;
    // End of variables declaration//GEN-END:variables
}
