/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panchayatoperator;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import vegetabletrading.EmpLogin;
import vegetabletrading.HomePage;
import vegetabletrading.ParabitDB;
import vegetabletrading.ScreenSize;

/**
 *
 * @author HARSHIT
 */
public class PO extends javax.swing.JFrame {
    ParabitDB db1,db2;
    String id,pcode,scode,date;
    int leftweight = 0,totalweight = 0;;
    
    /**
     * Creates new form MandiOperator
     */
    public PO(String a) {
        initComponents();
        id = a;
        fr.setVisible(false);
        tr.setVisible(false);
        vr.setVisible(false);
        dp.setVisible(false);
        st.setVisible(false);
        jPanel5.setVisible(false);
        alotvehpanel.setVisible(false);
        
        ScreenSize s = new ScreenSize();
        this.setSize(s.width, s.height);
        getData();
    }
    
    private void getData(){
        poid.setText("Operator Id : "+id);
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select * from employee where empid = "+id);
            db1.rs.next();
            String name = db1.rs.getString("name");
            poname.setText("Operator Name : "+name);
            pcode = db1.rs.getString("PostingID");
            panchcode.setText("Panchayat Code : "+pcode);
            scode = db1.rs.getString("StateCode");
            
            BufferedImage bi = ImageIO.read(db1.rs.getBinaryStream("EmpPhoto"));
            Image img = bi.getScaledInstance(110, 135, Image.SCALE_SMOOTH );
            poimg.setIcon(new ImageIcon(img));
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDateTime now = LocalDateTime.now();  
        date = (dtf.format(now));
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        reg = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        poid = new javax.swing.JLabel();
        panchcode = new javax.swing.JLabel();
        poname = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel5 = new javax.swing.JPanel();
        st = new javax.swing.JButton();
        fr = new javax.swing.JButton();
        tr = new javax.swing.JButton();
        vr = new javax.swing.JButton();
        dp = new javax.swing.JButton();
        alotvehpanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        alotvehtable = new javax.swing.JTable();
        allot = new javax.swing.JButton();
        tweight = new javax.swing.JTextField();
        lweight = new javax.swing.JTextField();
        vehtype = new javax.swing.JTextField();
        vehno = new javax.swing.JTextField();
        weightalloted = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        fueltype = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        poimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(950, 553));

        jPanel1.setBackground(new java.awt.Color(106, 200, 43));

        reg.setBackground(new java.awt.Color(106, 200, 43));
        reg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reg.setText("Registration");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(106, 200, 43));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Panchayat Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(106, 200, 43));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Daily Monitoring");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(106, 200, 43));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Allot Vehicle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel4.setText("  VEGETABLE TRADING");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(106, 200, 43));
        jPanel2.setPreferredSize(new java.awt.Dimension(836, 112));

        poid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        panchcode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        poname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton1.setBackground(java.awt.SystemColor.activeCaption);
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("PANCHAYAT OPERATOR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poid, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(14, 14, 14))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(panchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(poid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(poname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(744, 406));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(744, 406));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(744, 406));

        st.setText("Stock");
        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });

        fr.setText("Farmer Reg.");
        fr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                frMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                frMouseExited(evt);
            }
        });
        fr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frActionPerformed(evt);
            }
        });

        tr.setText("Transport Owner Reg.");
        tr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trMouseExited(evt);
            }
        });
        tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trActionPerformed(evt);
            }
        });

        vr.setText("Vegetable Reg.");
        vr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vrMouseExited(evt);
            }
        });
        vr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrActionPerformed(evt);
            }
        });

        dp.setText("Daliy Production");
        dp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dpMouseExited(evt);
            }
        });
        dp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fr)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(st)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(tr)))
                        .addGap(40, 40, 40)
                        .addComponent(vr)))
                .addGap(40, 40, 40)
                .addComponent(dp)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        alotvehpanel.setBackground(new java.awt.Color(255, 255, 255));

        alotvehtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S No.", "Vehicle No.", "Vehicle Type", "Fuel Type", "Weight Alloted", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        alotvehtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alotvehtableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(alotvehtable);

        allot.setText("ALLOT");
        allot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allotActionPerformed(evt);
            }
        });

        tweight.setText("Total Weight");
        tweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweightActionPerformed(evt);
            }
        });

        lweight.setText("Left Weight");
        lweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lweightActionPerformed(evt);
            }
        });

        vehtype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vehtype.setText("Vehicle Type");
        vehtype.setBorder(null);

        vehno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vehno.setText("Vehicle No.");
        vehno.setBorder(null);
        vehno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehnoActionPerformed(evt);
            }
        });

        weightalloted.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        weightalloted.setText("Weight Alloted");
        weightalloted.setBorder(null);

        amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amount.setText("Amount");
        amount.setBorder(null);

        fueltype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fueltype.setText("Fuel Type");
        fueltype.setBorder(null);

        jButton5.setText("Update");

        javax.swing.GroupLayout alotvehpanelLayout = new javax.swing.GroupLayout(alotvehpanel);
        alotvehpanel.setLayout(alotvehpanelLayout);
        alotvehpanelLayout.setHorizontalGroup(
            alotvehpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alotvehpanelLayout.createSequentialGroup()
                .addGroup(alotvehpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(alotvehpanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(tweight, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lweight, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(allot))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, alotvehpanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(alotvehpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(alotvehpanelLayout.createSequentialGroup()
                                .addComponent(vehno, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(vehtype, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(alotvehpanelLayout.createSequentialGroup()
                                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(weightalloted, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(alotvehpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fueltype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(30, 30, 30))
        );
        alotvehpanelLayout.setVerticalGroup(
            alotvehpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alotvehpanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(alotvehpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allot)
                    .addComponent(tweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(alotvehpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fueltype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(alotvehpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vehno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vehtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(alotvehpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightalloted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(alotvehpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(alotvehpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(alotvehpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        poimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(poimg, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(poimg, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        HomePage hpob = new HomePage();
        hpob.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed

        jPanel5.setVisible(true);
        alotvehpanel.setVisible(false);

        fr.setVisible(true);
        tr.setVisible(true);
        vr.setVisible(true);
        dp.setVisible(true);
        st.setVisible(false);
     
        // TODO add your handling code here:
    }//GEN-LAST:event_regActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        jPanel5.setVisible(false);
        alotvehpanel.setVisible(false);
        fr.setVisible(false);
        tr.setVisible(false);
        vr.setVisible(false);
        dp.setVisible(false);
        st.setVisible(false);
        
        PanchayatData pd = new PanchayatData(this,false,id);
        pd.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jPanel5.setVisible(true);
        alotvehpanel.setVisible(false);
        fr.setVisible(false);
        tr.setVisible(false);
        vr.setVisible(false);
        dp.setVisible(false);
        st.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void frActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frActionPerformed

        FarmerReg ob = new FarmerReg(this,true,id,pcode);
        ob.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_frActionPerformed

    private void trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trActionPerformed

        TransportOwner ob = new TransportOwner(this,true,id,pcode);
        ob.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_trActionPerformed

    private void vrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrActionPerformed

        VegetableReg ob = new VegetableReg(this,true,id,pcode);
        ob.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_vrActionPerformed

    private void dpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpActionPerformed

        DaliyProduction ob = new DaliyProduction(this,true,id,pcode);
        ob.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_dpActionPerformed

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed

        POStock ps = new POStock(this,false,id);
        ps.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_stActionPerformed

    private void alotvehtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alotvehtableMouseClicked
        vehtype.setVisible(true);
        vehno.setVisible(true);
        fueltype.setVisible(true);
        weightalloted.setVisible(true);
        amount.setVisible(true);
        
        
        int i = alotvehtable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)alotvehtable.getModel();
        
        vehno.setText("Vehicle No.: "+ model.getValueAt(i, 1).toString());
        vehtype.setText("Vehicle Type: "+ model.getValueAt(i, 2).toString());
        fueltype.setText("Fuel Type: "+ model.getValueAt(i, 3).toString());
        weightalloted.setText("Weight Alloted: "+ model.getValueAt(i,4).toString());
        amount.setText("Amount: "+ model.getValueAt(i, 5).toString());
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_alotvehtableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanel5.setVisible(false);
        alotvehpanel.setVisible(true);
        
        //vehtype.setVisible(false);
        //vehno.setVisible(false);
        //fueltype.setVisible(false);
        //weightalloted.setVisible(false);
        //amount.setVisible(false);
        
        
        totalweight = 0;
        try {
            String sql = "SELECT * FROM `pst"+scode+"` WHERE PCode = '"+ pcode +"' and RegDate = '"+ date +"';";
            //System.out.println(sql);
            db1 = new ParabitDB();
            db1.rs = db1.stm.executeQuery(sql);
            while(db1.rs.next())
            {
                int weight = Integer.parseInt(db1.rs.getString("TotalQua"));
                totalweight = totalweight + weight;
                tweight.setText("Total Weight: "+totalweight+" KG");
            }
        }catch (Exception e){
            System.out.println(e);      
        }
        
        leftweight = totalweight;
        try {
            String sql = "SELECT * FROM `allotedveh"+scode+"` WHERE PCode = '"+ pcode +"' and AllotementDate = '"+ date +"';";
            System.out.println(sql);
            db1 = new ParabitDB();
            DefaultTableModel model = (DefaultTableModel)alotvehtable.getModel();
            model.setRowCount(0);
            db1.rs = db1.stm.executeQuery(sql);
            int sno = 0;
            //to set date got from data base for transport owner vehicles
            while(db1.rs.next())
            {
                sno = sno + 1;
                String vehtype = db1.rs.getString("VehicleType");
                String vehno = db1.rs.getString("VehicleNo");
                String fueltype = db1.rs.getString("FuelType");
                int allotweight = db1.rs.getInt("WeightAlloted");
                leftweight = leftweight - allotweight;
                String price = db1.rs.getString("TotalMoney");
                model.addRow(new Object[]{sno,vehno,vehtype,fueltype,allotweight,price});
            }  
        } catch (Exception e)
        {
            System.out.println(e);      
        }
        lweight.setText("Left Weight: "+leftweight+" KG");
        System.out.println(leftweight);      
        
        if(leftweight > 0){
            allot.setVisible(true);
        }else{
            allot.setVisible(false);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void allotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allotActionPerformed
        try{
            String sql = "SELECT * FROM `availveh"+scode+"` WHERE PCode = '"+ pcode +"';";
            System.out.println(sql);
            db1 = new ParabitDB();
            db1.rs = db1.stm.executeQuery(sql);
            if(db1.rs.next()){
                new AllotVeh(pcode,leftweight);
            }else{
                sql = "SELECT * FROM `vehicledetails` WHERE PCode = '"+ pcode +"' and Status = '1';";
                System.out.println(sql);
                db1.rs = db1.stm.executeQuery(sql);
                db2 = new ParabitDB();
                while(db1.rs.next()){
                    String pcode = db1.rs.getString("PCode");
                    String toid = db1.rs.getString("TOID");
                    String vehno = db1.rs.getString("VehicleNo");
                    String vehtype = db1.rs.getString("VehicleType");
                    String fueltype = db1.rs.getString("FuelType");
                    int rate = db1.rs.getInt("Price");
                    int cap = db1.rs.getInt("Capacity");
                    db2.stm.executeUpdate("INSERT INTO `availveh"+scode+"`(`PCode`, `TOID`, `VehicleNo`, `VehicleType`, `FuelType`, `Rate`, `Capacity`) VALUES ('"+pcode+"','"+toid+"','"+vehno+"','"+vehtype+"','"+fueltype+"','"+rate+"','"+cap+"');");
                }
                new AllotVeh(pcode,leftweight);
            }
            
            leftweight = totalweight;
            sql = "SELECT * FROM `allotedveh"+scode+"` WHERE PCode = '"+ pcode +"' and AllotementDate = '"+ date +"';";
            System.out.println(sql);
            db1 = new ParabitDB();
            DefaultTableModel model = (DefaultTableModel)alotvehtable.getModel();
            model.setRowCount(0);
            db1.rs = db1.stm.executeQuery(sql);
            int sno = 0;
            //to set date got from data base for transport owner vehicles
            while(db1.rs.next())
            {
                sno = sno + 1;
                String vehtype = db1.rs.getString("VehicleType");
                String vehno = db1.rs.getString("VehicleNo");
                String fueltype = db1.rs.getString("FuelType");
                int allotweight = db1.rs.getInt("WeightAlloted");
                leftweight = leftweight - allotweight;
                String price = db1.rs.getString("TotalMoney");
                model.addRow(new Object[]{sno,vehno,vehtype,fueltype,allotweight,price});
            }  
        } catch (Exception e)
        {
            System.out.println(e);      
        }
        lweight.setText("Left Weight: "+leftweight+" KG");
        
        if(leftweight > 0){
            allot.setVisible(true);
        }else{
            allot.setVisible(false);
        }
        
        
        
    }//GEN-LAST:event_allotActionPerformed

    private void tweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tweightActionPerformed

    private void lweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lweightActionPerformed

    private void vehnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehnoActionPerformed

    private void frMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frMouseEntered
        fr.setBackground(Color.yellow);
        // TODO add your handling code here:
    }//GEN-LAST:event_frMouseEntered

    private void frMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frMouseExited
        fr.setBackground(Color.LIGHT_GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_frMouseExited

    private void trMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trMouseEntered
        tr.setBackground(Color.yellow);
        // TODO add your handling code here:
    }//GEN-LAST:event_trMouseEntered

    private void vrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vrMouseEntered
        vr.setBackground(Color.yellow);
        // TODO add your handling code here:
    }//GEN-LAST:event_vrMouseEntered

    private void trMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trMouseExited
        tr.setBackground(Color.LIGHT_GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_trMouseExited

    private void vrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vrMouseExited
        vr.setBackground(Color.LIGHT_GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_vrMouseExited

    private void dpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dpMouseExited
        dp.setBackground(Color.LIGHT_GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_dpMouseExited

    private void dpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dpMouseEntered
        dp.setBackground(Color.yellow);
        // TODO add your handling code here:
    }//GEN-LAST:event_dpMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                new PO(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allot;
    private javax.swing.JPanel alotvehpanel;
    private javax.swing.JTable alotvehtable;
    private javax.swing.JTextField amount;
    private javax.swing.JButton dp;
    private javax.swing.JButton fr;
    private javax.swing.JTextField fueltype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lweight;
    private javax.swing.JLabel panchcode;
    private javax.swing.JLabel poid;
    private javax.swing.JLabel poimg;
    private javax.swing.JLabel poname;
    private javax.swing.JButton reg;
    private javax.swing.JButton st;
    private javax.swing.JButton tr;
    private javax.swing.JTextField tweight;
    private javax.swing.JTextField vehno;
    private javax.swing.JTextField vehtype;
    private javax.swing.JButton vr;
    private javax.swing.JTextField weightalloted;
    // End of variables declaration//GEN-END:variables
}
