/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package panchayatoperator;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;
import vegetabletrading.ParabitDB;
import vegetabletrading.Mail;

/**
 *
 * @author HARSHIT
 */
public class TransportOwner extends javax.swing.JDialog {
    ParabitDB db1;
    ParabitDB db2;
    ParabitDB db3;
    ParabitDB db4;
    PBThread pb;
    Mail vm;
    Mail rsm;
    
    int toid = 0,sno = 0,emailotp;
    String state, aadhar, pathimg, pathsign, pathimg1, pathimg2, pathimg3, pathimg4,poid,pcode;
    /**
     * Creates new form TransportOwner
     */
    public TransportOwner(java.awt.Frame parent, boolean modal,String a, String b) {
        super(parent, modal);
        initComponents();
        poid = a;
        pcode = b;
        
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("select statename from statecode order by statename");
          
            while(db1.rs.next())
            {
                tostate.addItem(db1.rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        personalsave.setVisible(false);
    }
    
    class PBThread extends Thread
    {
        JProgressBar pbar;
        
        PBThread(JProgressBar pbar)
        {
            pbar = tovehpbar;
        }
        
        public void run()
        {
            int min = 0;
            int max = 50;
            
            tovehpbar.setMaximum(min);
            tovehpbar.setMaximum(max);
            tovehpbar.setValue(0);
            
            for(int i = min; i<max; i++)
            {
                tovehpbar.setValue(i);
                try {
                    sleep(30);
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tb1 = new javax.swing.JTabbedPane();
        personal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        toname = new javax.swing.JTextField();
        toregmob = new javax.swing.JTextField();
        toaltmob1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        toaltmob2 = new javax.swing.JTextField();
        tophoto = new javax.swing.JLabel();
        tophupload = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        toemail = new javax.swing.JTextField();
        topan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        toaadhar = new javax.swing.JTextField();
        todrivinglicence = new javax.swing.JTextField();
        personalsave = new javax.swing.JButton();
        topid = new javax.swing.JLabel();
        tosign = new javax.swing.JLabel();
        tosignupload = new javax.swing.JButton();
        todate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        otp = new javax.swing.JTextField();
        Verify = new javax.swing.JButton();
        address = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tohouse = new javax.swing.JTextField();
        tocity = new javax.swing.JTextField();
        tostreet = new javax.swing.JTextField();
        toblock = new javax.swing.JTextField();
        tocolony = new javax.swing.JTextField();
        totehsil = new javax.swing.JTextField();
        topincode = new javax.swing.JTextField();
        tostate = new javax.swing.JComboBox<>();
        todistrict = new javax.swing.JComboBox<>();
        addsave = new javax.swing.JButton();
        toaid = new javax.swing.JLabel();
        bankdetails = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tobank = new javax.swing.JTextField();
        toaccno = new javax.swing.JTextField();
        toifsc = new javax.swing.JTextField();
        tobranch = new javax.swing.JTextField();
        banksave = new javax.swing.JButton();
        tobid = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tovehcap = new javax.swing.JTextField();
        tovehno = new javax.swing.JTextField();
        tovehmodel = new javax.swing.JTextField();
        tovehtype = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tovehregno = new javax.swing.JTextField();
        tovehinsno = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        tovehpbar = new javax.swing.JProgressBar();
        tovehimg1 = new javax.swing.JButton();
        tovehimg2 = new javax.swing.JButton();
        tovehimg3 = new javax.swing.JButton();
        tovehimg4 = new javax.swing.JButton();
        tovehsub = new javax.swing.JButton();
        tovid = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        totable = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        tovehrexdate = new com.toedter.calendar.JDateChooser();
        tovehiexdate = new com.toedter.calendar.JDateChooser();
        tovehfuel = new javax.swing.JComboBox<>();
        tovehnext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transport Registration");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel1.setText(" TRANSPORT OWNER ");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Name");

        jLabel3.setText("DOB");

        jLabel4.setText("Reg Mob No.");

        jLabel5.setText("Altenate Mob No. 1");
        jLabel5.setToolTipText("");

        toaltmob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toaltmob1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Alternate Mob No. 2");

        tophoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tophoto.setText("             Photo");
        tophoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tophoto.setPreferredSize(new java.awt.Dimension(134, 172));

        tophupload.setText("Upload");
        tophupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tophuploadActionPerformed(evt);
            }
        });

        jLabel8.setText("Aadhar No.");

        jLabel9.setText("Pan card No.");

        jLabel10.setText("Email Id");

        jLabel11.setText("Driving Licence No.");

        personalsave.setText("Save and Next");
        personalsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalsaveActionPerformed(evt);
            }
        });

        topid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tosign.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tosign.setText("           Signature");
        tosign.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tosign.setPreferredSize(new java.awt.Dimension(151, 50));
        tosign.setVerifyInputWhenFocusTarget(false);

        tosignupload.setText("Upload");
        tosignupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tosignuploadActionPerformed(evt);
            }
        });

        jButton1.setText("Send OTP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel36.setText("Otp :");

        Verify.setText("Verify");
        Verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personalLayout = new javax.swing.GroupLayout(personal);
        personal.setLayout(personalLayout);
        personalLayout.setHorizontalGroup(
            personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalLayout.createSequentialGroup()
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalLayout.createSequentialGroup()
                                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(todate, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(toname))
                                .addGap(217, 217, 217)
                                .addComponent(tophoto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(personalLayout.createSequentialGroup()
                                .addComponent(toregmob, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(245, 245, 245)
                                .addComponent(tophupload))
                            .addGroup(personalLayout.createSequentialGroup()
                                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(personalLayout.createSequentialGroup()
                                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(todrivinglicence, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(topan, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalLayout.createSequentialGroup()
                                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(toaltmob2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(toaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(30, 30, 30)
                                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toaltmob1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toemail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(otp, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(personalLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(topid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(personalsave)
                            .addComponent(tosign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(266, 266, 266))
                    .addGroup(personalLayout.createSequentialGroup()
                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(tosignupload))
                            .addGroup(personalLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Verify, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))))
                        .addContainerGap())))
        );
        personalLayout.setVerticalGroup(
            personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalLayout.createSequentialGroup()
                        .addComponent(topid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(toname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(todate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(toregmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personalLayout.createSequentialGroup()
                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tophoto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personalLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(tosign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tosignupload)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tophupload)))
                .addGap(31, 31, 31)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toaltmob2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(toaltmob1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(toemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(39, 39, 39)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(otp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Verify))
                    .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(todrivinglicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalsave)
                    .addComponent(topan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(57, 57, 57))
        );

        tb1.addTab("Personal Details", personal);

        jLabel13.setText("House No.");

        jLabel14.setText("City/Village");

        jLabel15.setText("State");

        jLabel16.setText("Street");

        jLabel17.setText("Block");

        jLabel18.setText("District");

        jLabel19.setText("Colony");

        jLabel20.setText("Tehsil");

        jLabel21.setText("PinCode");

        tostate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose State" }));
        tostate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tostateActionPerformed(evt);
            }
        });

        todistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose District" }));
        todistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todistrictActionPerformed(evt);
            }
        });

        addsave.setText("Save and Next");
        addsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsaveActionPerformed(evt);
            }
        });

        toaid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout addressLayout = new javax.swing.GroupLayout(address);
        address.setLayout(addressLayout);
        addressLayout.setHorizontalGroup(
            addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressLayout.createSequentialGroup()
                .addGroup(addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addressLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tocity, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tostate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tohouse, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tostreet, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toblock)
                            .addComponent(todistrict, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tocolony, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totehsil)
                            .addComponent(topincode)))
                    .addGroup(addressLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(toaid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addressLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addsave)
                .addGap(115, 115, 115))
        );
        addressLayout.setVerticalGroup(
            addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(toaid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(tohouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tostreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tocolony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(tocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toblock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totehsil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21)
                    .addComponent(topincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tostate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(addsave)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        tb1.addTab("Address", address);

        jLabel23.setText("Bank Name");

        jLabel24.setText("Account No.");

        jLabel25.setText("IFSC Code");

        jLabel26.setText("Branch Name");

        toaccno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toaccnoActionPerformed(evt);
            }
        });

        banksave.setText("Save and Next");
        banksave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banksaveActionPerformed(evt);
            }
        });

        tobid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout bankdetailsLayout = new javax.swing.GroupLayout(bankdetails);
        bankdetails.setLayout(bankdetailsLayout);
        bankdetailsLayout.setHorizontalGroup(
            bankdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bankdetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(banksave)
                .addGap(211, 211, 211))
            .addGroup(bankdetailsLayout.createSequentialGroup()
                .addGroup(bankdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bankdetailsLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(bankdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(bankdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toaccno)
                            .addComponent(tobank, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(91, 91, 91)
                        .addGroup(bankdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(bankdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toifsc)
                            .addComponent(tobranch, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(bankdetailsLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(tobid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bankdetailsLayout.setVerticalGroup(
            bankdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankdetailsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tobid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(bankdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26)
                    .addComponent(tobank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tobranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(bankdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(toaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toifsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(72, 72, 72)
                .addComponent(banksave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tb1.addTab("Bank Details", bankdetails);

        jLabel7.setText("Vehicle Type");

        jLabel12.setText("Vehicle No.");

        jLabel22.setText("Vehicle Capacity");

        jLabel27.setText("Fuel Type");

        tovehno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehnoActionPerformed(evt);
            }
        });

        tovehtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Vehicle Type", "Truck", "Mini Truck", "Pickup", "Loading Auto", "Tractor with Trolly" }));

        jLabel28.setText("Vehicle Reg No.");

        jLabel29.setText("Vehicle Reg Expire Date");

        jLabel30.setText("Vehicle Insurance No.");

        jLabel31.setText("Vehicle Insurance Expire Date");

        tovehregno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehregnoActionPerformed(evt);
            }
        });

        jLabel32.setText("Vehicle Image :");

        tovehimg1.setText("Upload");
        tovehimg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehimg1ActionPerformed(evt);
            }
        });

        tovehimg2.setText("Upload");
        tovehimg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehimg2ActionPerformed(evt);
            }
        });

        tovehimg3.setText("Upload");
        tovehimg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehimg3ActionPerformed(evt);
            }
        });

        tovehimg4.setText("Upload");
        tovehimg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehimg4ActionPerformed(evt);
            }
        });

        tovehsub.setText("Submit / Register");
        tovehsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehsubActionPerformed(evt);
            }
        });

        tovid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        totable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S No.", "Vehicle Type", "Vehicle No.", "Vehicle Model ", "Fuel Type", "Reg No and Exp Date", "Ins No and Exp Date", "Capacity", "Vehicle Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(totable);
        if (totable.getColumnModel().getColumnCount() > 0) {
            totable.getColumnModel().getColumn(0).setPreferredWidth(30);
            totable.getColumnModel().getColumn(1).setPreferredWidth(60);
            totable.getColumnModel().getColumn(2).setPreferredWidth(60);
            totable.getColumnModel().getColumn(3).setPreferredWidth(60);
            totable.getColumnModel().getColumn(4).setPreferredWidth(50);
            totable.getColumnModel().getColumn(5).setPreferredWidth(110);
            totable.getColumnModel().getColumn(6).setPreferredWidth(110);
            totable.getColumnModel().getColumn(7).setPreferredWidth(60);
            totable.getColumnModel().getColumn(8).setPreferredWidth(60);
        }

        jLabel33.setText("Vehicle Model");

        tovehrexdate.setFocusTraversalPolicyProvider(true);

        tovehfuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Fuel Type", "Petrol", "Desiel", "CNG" }));

        tovehnext.setText("Next");
        tovehnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tovehnextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tovehtype, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tovehmodel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tovehcap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(tovehno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tovehfuel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tovehregno, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(tovehinsno))
                                    .addComponent(tovehpbar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tovehrexdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tovehiexdate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(tovehimg1)
                                        .addGap(50, 50, 50)
                                        .addComponent(tovehimg2)
                                        .addGap(50, 50, 50)
                                        .addComponent(tovehimg3)
                                        .addGap(50, 50, 50)
                                        .addComponent(tovehimg4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tovehnext)))))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(tovid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tovehsub)
                .addGap(101, 101, 101))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tovid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel27)
                                    .addComponent(tovehno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tovehtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tovehfuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(tovehcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33)
                                    .addComponent(tovehmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(tovehregno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tovehrexdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(tovehinsno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tovehiexdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tovehimg1)
                        .addComponent(tovehimg2)
                        .addComponent(tovehimg3)
                        .addComponent(tovehimg4)
                        .addComponent(tovehnext))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tovehpbar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tovehsub)
                .addGap(261, 261, 261))
        );

        tb1.addTab("Vehicle Details", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(405, 405, 405))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tb1, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toaccnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toaccnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toaccnoActionPerformed

    private void tovehregnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehregnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tovehregnoActionPerformed

    private void tovehnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tovehnoActionPerformed

    private void tovehsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehsubActionPerformed

        DefaultTableModel model = (DefaultTableModel)totable.getModel();
        
        db3 = new ParabitDB();
        try{ 
            String vsattribute = "`TOID`, `VehicleType`, `VehicleNo`, `VehicleModel`, `FuelType`, `VehRegNo`, `RegExpDate`, `VehInsNo`, `InsExpDate`, `Capacity`, Image1, Image2, Image3, Image4, `VehRegDate`, POID, PCode";
            //System.out.println(vsattribute);
            
            for(int i =0; i<model.getRowCount(); i++){
                String vehtype = model.getValueAt(i, 1).toString();
                String vehno = model.getValueAt(i, 2).toString();
                String vehmodel = model.getValueAt(i, 3).toString();
                String fueltype = model.getValueAt(i, 4).toString();
                String regnodt = model.getValueAt(i, 5).toString();
                String insnodt = model.getValueAt(i, 6).toString();
                String cap = model.getValueAt(i, 7).toString();
                String img = model.getValueAt(i, 8).toString();
                
                String[] reg = regnodt.split(", ");
                String[] ins = insnodt.split(", ");
                
                String[] image = img.split(",  ");
                                
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
                LocalDateTime now = LocalDateTime.now();  
                String date = (dtf.format(now));
                              
                String vsvalue = toid+"','"+vehtype+"','"+vehno+"','"+vehmodel+"','"+fueltype+"','"+reg[0]+"','"+reg[1]+"','"+ins[0]+"','"+ins[1]+"','"+cap+"',?"+",?"+",?"+",?,'"+date+"','"+poid+"','"+pcode;
               // System.out.println(vsvalue);
                
                String qvs = "insert into vehicledetails ("+vsattribute+") values('"+vsvalue+"')";
                System.out.println(qvs);
                             
                db1.pst = db1.con.prepareStatement(qvs);
            
                InputStream img1 = new FileInputStream(image[0]);
                InputStream img2 = new FileInputStream(image[1]);
                InputStream img3 = new FileInputStream(image[2]);
                InputStream img4 = new FileInputStream(image[3]);
                        
                db1.pst.setBlob(1, img1);
                db1.pst.setBlob(2, img2);
                db1.pst.setBlob(3, img3);
                db1.pst.setBlob(4, img4);
                    
                db1.pst.executeUpdate();
                
            }
            rsm = new Mail(toemail.getText(),toname.getText());
            JOptionPane.showMessageDialog(this,"Registered Successfully!!!");
        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
        }               
             
        
        
        DefaultTableModel farmodel = (DefaultTableModel)totable.getModel();
        farmodel.setRowCount(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_tovehsubActionPerformed

    private void personalsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalsaveActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                           
        String s1,s2,s3,s4,s5,s6,s8,s9;
        
        s1 = toname.getText();
        s2 = sdf.format(todate.getDate());
        s3 = toregmob.getText();
        s4 = toaltmob1.getText();
        s5 = toaltmob2.getText();
        s6 = toemail.getText();
        aadhar = toaadhar.getText();
        s8 = topan.getText();
        s9 = todrivinglicence.getText();
                
        String psvalue = s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+aadhar+"','"+s8+"',?,?,'"+s9+"','"+poid+"','"+pcode;
       // System.out.println(psvalue);
        
        String psattribute = "TOName, DOB, RegMobNo, AltMobNo1, AltMobNo2, EmailId, AadharNo, PANNo, TOphoto, Signature, DLNo, POID, PCode";
       // System.out.println(psattribute);
                
        String qps = "insert into transportowner ("+psattribute+") values('"+psvalue+"')";
        System.out.println(qps);
        
        // To insert values of this tab in database
        
        db2 = new ParabitDB();
        try
        {
            db2.rs = db2.stm.executeQuery("SELECT * FROM `transportowner` WHERE AadharNo = '"+ aadhar +"'");
            boolean check = db2.rs.next();
            if(check){
                JOptionPane.showMessageDialog(this,"Already registered...");
                this.setVisible(false);
            }else{
                db3 = new ParabitDB();
                db3.pst = db3.con.prepareStatement(qps);
            
                InputStream img = new FileInputStream(pathimg);
                InputStream sign = new FileInputStream(pathsign);             
          
                db3.pst.setBlob(1, img);
                db3.pst.setBlob(2, sign);         
   
                db3.pst.executeUpdate();
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        // To get value of fid from database
        db4 = new ParabitDB();
        try
        {
            db4.rs = db4.stm.executeQuery("select TOID from transportowner where aadharNo = "+ aadhar);
           
              db4.rs.next();
              toid = db4.rs.getInt(1);
                  
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        topid.setText("Transport Owner Id : "+toid);
        toaid.setText("Transport Owner Id : "+toid);
        tobid.setText("Transport Owner Id : "+toid);
        tovid.setText("Transport Owner Id : "+toid);
        
        //To go to next tab
        int i = tb1.getSelectedIndex();
        tb1.setSelectedIndex(i+1);

        // TODO add your handling code here:
    }//GEN-LAST:event_personalsaveActionPerformed

    private void tophuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tophuploadActionPerformed

        String path = null;
       
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path = f.getAbsolutePath();
        pathimg = path;
        //System.out.println(path);
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            tophoto.setIcon(icon);
            
                // TODO add your handling code here:
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tophuploadActionPerformed

    private void tosignuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tosignuploadActionPerformed

        String path = null;

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path = f.getAbsolutePath();
        pathsign = path;

        //System.out.println(path);
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image im = bi.getScaledInstance(151, 50, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(im);
            tosign.setIcon(icon);

            // TODO add your handling code here:
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tosignuploadActionPerformed

    private void addsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsaveActionPerformed

        String s1,s2,s3,s4,s5,s6,s7,s8,s9;
      
        s1 = tohouse.getText();
        s2 = tostreet.getText();
        s3 = tocolony.getText();
        s4 = tocity.getText();
        s5 = toblock.getText();       
        s6 = totehsil.getText();
        s7 = (String)tostate.getSelectedItem();
        s8 = (String)todistrict.getSelectedItem();
        s9 = topincode.getText();
        
        //String asvalue = s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+s7+"','"+s8+"','"+s9;
        //System.out.println(asvalue);
                
        String qas = "UPDATE transportowner SET HouseNo ='"+s1+"', Street ='"+s2+"', Colony ='"+s3+"', CityVillage ='"+s4+"', Block ='"+s5+"', Tehsil ='"+s6+"', State ='"+s7+"', Dist ='"+s8+"', Pincode ='"+s9+"' where AadharNo = " + aadhar;
        System.out.println(qas);
        
        // To insert values of this tab in database
        db3 = new ParabitDB();
        try
        {
            db3.stm.executeUpdate(qas);
        
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        //To go to next tab
        int i = tb1.getSelectedIndex();
        tb1.setSelectedIndex(i+1);

        // TODO add your handling code here:
    }//GEN-LAST:event_addsaveActionPerformed

    private void banksaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banksaveActionPerformed

        String s1,s2,s3,s4,s5;
        s1 = tobank.getText();
        s2 = toaccno.getText();
        s3 = toifsc.getText();
        s4 = tobranch.getText();
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDateTime now = LocalDateTime.now();  
        s5 = (dtf.format(now));
        
        //String bsvalue = s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5;
        //System.out.println(bsvalue);
        
        String qbs = "UPDATE transportowner SET BName ='"+s1+"', BAccNo ='"+s2+"', BIFSC ='"+s3+"', BBranch ='"+s4+"', RegDate ='"+s5+"' where AadharNo = " + aadhar;
        System.out.println(qbs);
        
        // To insert values of this tab in database
        db3 = new ParabitDB();
        try
        {
            db3.stm.executeUpdate(qbs);
        
        }catch(Exception e)
        {
            System.out.println(e);
        }
                
        //To go to next tab
        int i = tb1.getSelectedIndex();
        tb1.setSelectedIndex(i+1);

        // TODO add your handling code here:
    }//GEN-LAST:event_banksaveActionPerformed

    private void tostateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tostateActionPerformed

        state = tostate.getSelectedItem().toString();
        System.out.println(state);
        
        db2 = new ParabitDB();
        try
        {
            db2.rs = db2.stm.executeQuery("select distinct distname from districtcode where statecode = (select statecode from statecode where statename = '" + state + "') order by distname");
            
            while(db2.rs.next())
            {
                todistrict.addItem(db2.rs.getString(1));  
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tostateActionPerformed

    private void tovehnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehnextActionPerformed
    
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                
        String s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,img;
        
        sno = sno + 1;
        s1 = (String)tovehtype.getSelectedItem();
        s2 = tovehno.getText();
        s3 = tovehmodel.getText();
        s4 = (String)tovehfuel.getSelectedItem();
        s5 = tovehregno.getText();
        s6 = sdf.format(tovehrexdate.getDate());
        s7 = tovehinsno.getText();
        s8 = sdf.format(tovehiexdate.getDate());
        s9 = tovehcap.getText();
        s10 = s5+", "+s6;
        s11 = s7+", "+s8;
        
        img = pathimg1+",  "+pathimg2+",  "+pathimg3+",  "+pathimg4;
        
        DefaultTableModel model = (DefaultTableModel)totable.getModel();
        model.addRow(new Object[]{sno,s1,s2,s3,s4,s10,s11,s9,img});
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_tovehnextActionPerformed

    private void tovehimg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehimg1ActionPerformed

        String path1 = null;
       
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path1 = f.getAbsolutePath();
        pathimg1 = path1;
       // System.out.println(path1);
        try {
            BufferedImage bi = ImageIO.read(new File(path1));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);
            
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pb = new PBThread(tovehpbar);
        pb.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_tovehimg1ActionPerformed

    private void tovehimg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehimg2ActionPerformed

        String path2 = null;
       
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path2 = f.getAbsolutePath();
        pathimg2 = path2;
       // System.out.println(path2);
        try {
            BufferedImage bi = ImageIO.read(new File(path2));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);
            
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pb = new PBThread(tovehpbar);
        pb.start();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tovehimg2ActionPerformed

    private void tovehimg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehimg3ActionPerformed

        String path3 = null;
       
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path3 = f.getAbsolutePath();
        pathimg3 = path3;
        //System.out.println(path3);
        try {
            BufferedImage bi = ImageIO.read(new File(path3));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);
            
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pb = new PBThread(tovehpbar);
        pb.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_tovehimg3ActionPerformed

    private void tovehimg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tovehimg4ActionPerformed

        String path4 = null;
       
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path4 = f.getAbsolutePath();
        pathimg4 = path4;
       // System.out.println(path4);
        try {
            BufferedImage bi = ImageIO.read(new File(path4));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);
            
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        pb = new PBThread(tovehpbar);
        pb.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_tovehimg4ActionPerformed

    private void toaltmob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toaltmob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toaltmob1ActionPerformed

    private void VerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyActionPerformed

        int otpval = Integer.parseInt(otp.getText());
        try
        {
            if(otpval==emailotp){
                JOptionPane.showMessageDialog(null,"OTP Verified...");
                personalsave.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Valid OTP!!!");
            }

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_VerifyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String emailid = toemail.getText();
        
        if(emailid!= "null")
        {            
            vm = new Mail(emailid);
            emailotp = vm.oneTimePass();
            System.out.println(emailotp);
        }
        else{
            JOptionPane.showMessageDialog(this,"Enter valid email...");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void todistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todistrictActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransportOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransportOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransportOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransportOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                String b = null;
                TransportOwner dialog = new TransportOwner(new javax.swing.JFrame(), true,a,b);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Verify;
    private javax.swing.JPanel address;
    private javax.swing.JButton addsave;
    private javax.swing.JPanel bankdetails;
    private javax.swing.JButton banksave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField otp;
    private javax.swing.JPanel personal;
    private javax.swing.JButton personalsave;
    private javax.swing.JTabbedPane tb1;
    private javax.swing.JTextField toaadhar;
    private javax.swing.JTextField toaccno;
    private javax.swing.JLabel toaid;
    private javax.swing.JTextField toaltmob1;
    private javax.swing.JTextField toaltmob2;
    private javax.swing.JTextField tobank;
    private javax.swing.JLabel tobid;
    private javax.swing.JTextField toblock;
    private javax.swing.JTextField tobranch;
    private javax.swing.JTextField tocity;
    private javax.swing.JTextField tocolony;
    private com.toedter.calendar.JDateChooser todate;
    private javax.swing.JComboBox<String> todistrict;
    private javax.swing.JTextField todrivinglicence;
    private javax.swing.JTextField toemail;
    private javax.swing.JTextField tohouse;
    private javax.swing.JTextField toifsc;
    private javax.swing.JTextField toname;
    private javax.swing.JTextField topan;
    private javax.swing.JLabel tophoto;
    private javax.swing.JButton tophupload;
    private javax.swing.JLabel topid;
    private javax.swing.JTextField topincode;
    private javax.swing.JTextField toregmob;
    private javax.swing.JLabel tosign;
    private javax.swing.JButton tosignupload;
    private javax.swing.JComboBox<String> tostate;
    private javax.swing.JTextField tostreet;
    private javax.swing.JTable totable;
    private javax.swing.JTextField totehsil;
    private javax.swing.JTextField tovehcap;
    private javax.swing.JComboBox<String> tovehfuel;
    private com.toedter.calendar.JDateChooser tovehiexdate;
    private javax.swing.JButton tovehimg1;
    private javax.swing.JButton tovehimg2;
    private javax.swing.JButton tovehimg3;
    private javax.swing.JButton tovehimg4;
    private javax.swing.JTextField tovehinsno;
    private javax.swing.JTextField tovehmodel;
    private javax.swing.JButton tovehnext;
    private javax.swing.JTextField tovehno;
    private javax.swing.JProgressBar tovehpbar;
    private javax.swing.JTextField tovehregno;
    private com.toedter.calendar.JDateChooser tovehrexdate;
    private javax.swing.JButton tovehsub;
    private javax.swing.JComboBox<String> tovehtype;
    private javax.swing.JLabel tovid;
    // End of variables declaration//GEN-END:variables
}
