/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package panchayatoperator;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import static java.lang.Thread.sleep;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import vegetabletrading.ParabitDB;

/**
 *
 * @author HARSHIT
 */
public class VegetableReg extends javax.swing.JDialog {
    ParabitDB db1;
    ParabitDB db2;
    ParabitDB db3;
    PBThread pb;

    int id = 0;
    String pathimg1,pathimg2,pathimg3,pathimg4,poid,pcode;
    
    /**
     * Creates new form VegetableReg
     */
    public VegetableReg(java.awt.Frame parent, boolean modal, String a, String b) {
        super(parent, modal);
        initComponents();
        poid = a;
        pcode = b;
        
        vegqactual.setVisible(false);
        jLabel15.setVisible(false);
        
        //for vegetable name
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("SELECT Name,Image FROM productlist ORDER BY Name;");
            //db1.rs.next();            
            while(db1.rs.next())
            {
                vegname.addItem(db1.rs.getString(1));
               // vegname.addItem(db1.rs.getString(2));
               
               
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }        
        
        //for hindi name
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("SELECT HName FROM productlist ORDER BY HName;");
            //db1.rs.next();
            while(db1.rs.next())
            {
                veghindiname.addItem(db1.rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }

        
        //for vegetable regional name
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("SELECT RName FROM productlist ORDER BY RName;");
           // db1.rs.next();
            while(db1.rs.next())
            {
                vegregname.addItem(db1.rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
         //for vegetable colour
        db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("SELECT Colour FROM productlist ORDER BY Colour;");
           // db1.rs.next();
            while(db1.rs.next())
            {
                vegcolour.addItem(db1.rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    
    class PBThread extends Thread
    {
        JProgressBar pbar;
        
        PBThread(JProgressBar pbar)
        {
            pbar = vegprogressbar;
        }
        
        public void run()
        {
            int min = 0;
            int max = 50;
            
            vegprogressbar.setMaximum(min);
            vegprogressbar.setMaximum(max);
            vegprogressbar.setValue(0);
            
            for(int i = min; i<max; i++)
            {
                vegprogressbar.setValue(i);
                try {
                    sleep(30);
                }catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vegfarid = new javax.swing.JTextField();
        vegqplanted = new javax.swing.JTextField();
        veglccoord = new javax.swing.JTextField();
        vegarea = new javax.swing.JTextField();
        vegqexpected = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        vegname = new javax.swing.JComboBox<>();
        veghindiname = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vegid = new javax.swing.JLabel();
        vegorganic = new javax.swing.JRadioButton();
        veginorganic = new javax.swing.JRadioButton();
        vegcat = new javax.swing.JComboBox<>();
        vegcutdate = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        vegqactual = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        vegimg = new javax.swing.JLabel();
        vegprogressbar = new javax.swing.JProgressBar();
        vegimgup1 = new javax.swing.JButton();
        vegimgup2 = new javax.swing.JButton();
        vegimpup3 = new javax.swing.JButton();
        vegimgup4 = new javax.swing.JButton();
        vegsubreg = new javax.swing.JButton();
        vegcutmonth = new com.toedter.calendar.JMonthChooser();
        vegcutyear = new com.toedter.calendar.JYearChooser();
        jLabel10 = new javax.swing.JLabel();
        vegcolour = new javax.swing.JComboBox<>();
        vegregname = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vegetable Registration");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText(" VEGETABLE REGISTRATION ");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Farmer ID ");

        jLabel3.setText("Vegetable Name");

        jLabel4.setText("Vegetable Type");

        jLabel5.setText("Area For Production");

        jLabel6.setText("Hindi Name");

        vegfarid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegfaridActionPerformed(evt);
            }
        });

        vegarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegareaActionPerformed(evt);
            }
        });

        jLabel7.setText("Vegetable Category");

        vegname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Vegetable Name" }));
        vegname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vegnameMouseEntered(evt);
            }
        });
        vegname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegnameActionPerformed(evt);
            }
        });

        veghindiname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Hindi Name" }));
        veghindiname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veghindinameActionPerformed(evt);
            }
        });

        jLabel8.setText("Regional Name");

        jLabel9.setText("Estimated Date to Cut");

        vegid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vegid.setText(" Vegetable Id :  ");

        buttonGroup1.add(vegorganic);
        vegorganic.setText("Organic");

        buttonGroup1.add(veginorganic);
        veginorganic.setText("Inorganic");
        veginorganic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veginorganicActionPerformed(evt);
            }
        });

        vegcat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Category", "1", "1", "1", "1" }));
        vegcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegcatActionPerformed(evt);
            }
        });

        vegcutdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel11.setText("Land Center Coordinates");

        jLabel12.setText("Vegetable Quantity :");

        jLabel13.setText("Planted ");

        jLabel14.setText("Expected");

        jLabel15.setText("Actual");

        jLabel16.setText("Product / land Image :");

        vegimg.setText("        Vegetable Image");
        vegimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        vegimgup1.setText("Upload");
        vegimgup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegimgup1ActionPerformed(evt);
            }
        });

        vegimgup2.setText("Upload");
        vegimgup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegimgup2ActionPerformed(evt);
            }
        });

        vegimpup3.setText("Upload");
        vegimpup3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegimpup3ActionPerformed(evt);
            }
        });

        vegimgup4.setText("Upload");
        vegimgup4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegimgup4ActionPerformed(evt);
            }
        });

        vegsubreg.setText("Submit / Register");
        vegsubreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegsubregActionPerformed(evt);
            }
        });

        jLabel10.setText("Vegetable Colour");

        vegcolour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Colour" }));
        vegcolour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegcolourActionPerformed(evt);
            }
        });

        vegregname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Regional Name" }));
        vegregname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegregnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vegimgup1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vegfarid, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(vegqplanted)
                            .addComponent(vegarea)
                            .addComponent(vegname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(vegorganic, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(veginorganic, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(vegimgup2))
                            .addComponent(vegprogressbar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(vegid, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(vegcat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vegqexpected)
                                .addComponent(veglccoord, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(veghindiname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(vegimpup3)
                        .addGap(96, 96, 96)
                        .addComponent(vegimgup4)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vegsubreg)
                    .addComponent(vegqactual, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vegimg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vegcutdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vegcutmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vegcutyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(vegregname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vegcolour, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(vegid)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(vegfarid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(vegimg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(vegname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veghindiname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(vegregname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vegcutyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vegcutmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(vegorganic)
                            .addComponent(veginorganic)
                            .addComponent(vegcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(vegcolour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(vegarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(veglccoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(vegcutdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vegqplanted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vegqexpected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(vegqactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16))
                    .addComponent(vegprogressbar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vegimgup1)
                    .addComponent(vegimgup2)
                    .addComponent(vegimpup3)
                    .addComponent(vegimgup4)
                    .addComponent(vegsubreg))
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void veginorganicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veginorganicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veginorganicActionPerformed

    private void vegsubregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegsubregActionPerformed

        String date = (String)vegcutdate.getSelectedItem();
        int month= vegcutmonth.getMonth()+1;
        int year= vegcutyear.getYear();
                 
        String s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,vegtype="";
        
        s1 = vegfarid.getText();
        s2 = (String)vegname.getSelectedItem();
        s3 = (String)veghindiname.getSelectedItem();
        s4 = (String)vegregname.getSelectedItem();
        
        if(vegorganic.isSelected())
        {
            vegtype = "Organic";
        }
        if(veginorganic.isSelected())
        {
            vegtype = "Inorganic";
        }
        s5 = vegtype ;
        s6 = (String)vegcat.getSelectedItem();
        s7 = (String)vegcolour.getSelectedItem();
        s8 = vegarea.getText();
        s9 = veglccoord.getText();
        s10 = year+"-"+month+"-"+date;
        s11 = vegqplanted.getText();
        s12 = vegqexpected.getText();
        //s13 = vegqactual.getText();
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDateTime now = LocalDateTime.now();  
        s14 = (dtf.format(now));
        
        String vegvalue = id+"','"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+s7+"','"+s8+"','"+s9+"','"+s10+"','"+s11+"','"+s12+"',?"+",?"+",?"+",?,'"+s14+"','"+poid+"','"+pcode;
        //System.out.println(vegvalue);
        
        String vegattribute = "VegID, FID, VName, HName, RName, VegType, VegCategory, VegColour, VegProductAr, LandCoord, DateToCut, PlantQua, ExpQua, Image1, Image2, Image3, Image4, RegDate, POID, PCode";
        //System.out.println(vegattribute);
                
        String qveg = "insert into vegetablereg ("+vegattribute+") values('"+vegvalue+"')";
        System.out.println(qveg);
        
        db3 = new ParabitDB();
        try
        {
            db3.pst = db3.con.prepareStatement(qveg);
            
            InputStream img1 = new FileInputStream(pathimg1);
            InputStream img2 = new FileInputStream(pathimg2);
            InputStream img3 = new FileInputStream(pathimg3);
            InputStream img4 = new FileInputStream(pathimg4);             
          
            db3.pst.setBlob(1, img1);
            db3.pst.setBlob(2, img2);
            db3.pst.setBlob(3, img3);
            db3.pst.setBlob(4, img4);
                    
            db3.pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Registered Successfully!!!");
            
        }catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Fill All The Details...");
           
        }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_vegsubregActionPerformed

    private void vegareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vegareaActionPerformed

    private void vegnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegnameActionPerformed

        String name = (String)vegname.getSelectedItem();
        db3 = new ParabitDB();
        
        String qimg = "SELECT Image FROM productlist WHERE name = '" + name + "'";
            
        try {
          
            db3.rs = db3.stm.executeQuery(qimg);
            db3.rs.next();
            BufferedImage bi = ImageIO.read(db3.rs.getBinaryStream("Image"));
            Image img = bi.getScaledInstance(150, 150, Image.SCALE_SMOOTH );
            vegimg.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            System.out.println(e);
        }
        
       //for hindi name
        db3 = new ParabitDB();
        try
        {
            db3.rs = db3.stm.executeQuery("SELECT HName FROM productlist WHERE name = '"+name+"'");
                        
            while(db3.rs.next())
            {
                String hname = db3.rs.getString(1);
                veghindiname.setSelectedItem(hname);
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        //for vegetable regional name
        db1 = new ParabitDB();
        try
        {
            String q = "SELECT RName FROM productlist WHERE name = '"+name+"'";
            db1.rs = db1.stm.executeQuery(q);
                      
            while(db1.rs.next())
            {
                String rname = db1.rs.getString(1);
                vegregname.setSelectedItem(rname);
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        // To get value of id from database
        db2 = new ParabitDB();
        try
        {
            db2.rs = db2.stm.executeQuery("select SNo from productlist where Name = '"+ name +"'");
           
              db2.rs.next();
              id = db2.rs.getInt(1);
                  
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        vegid.setText("Vegetable Id : "+id);
              
        // TODO add your handling code here:
    }//GEN-LAST:event_vegnameActionPerformed

    private void vegimgup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegimgup1ActionPerformed

        String path1 = null;
       
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path1 = f.getAbsolutePath();
        pathimg1 = path1;
        //System.out.println(path1);
        try {
            BufferedImage bi = ImageIO.read(new File(path1));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);
            
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pb = new PBThread(vegprogressbar);
        pb.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_vegimgup1ActionPerformed

    private void vegimgup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegimgup2ActionPerformed

        String path2 = null;
       
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path2 = f.getAbsolutePath();
        pathimg2 = path2;
       // System.out.println(path2);
        try {
            BufferedImage bi = ImageIO.read(new File(path2));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);
            
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pb = new PBThread(vegprogressbar);
        pb.start();
        // TODO add your handling code here:
    }//GEN-LAST:event_vegimgup2ActionPerformed

    private void vegimpup3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegimpup3ActionPerformed

        String path3 = null;
       
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path3 = f.getAbsolutePath();
        pathimg3 = path3;
       // System.out.println(path3);
        try {
            BufferedImage bi = ImageIO.read(new File(path3));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);
            
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pb = new PBThread(vegprogressbar);
        pb.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_vegimpup3ActionPerformed

    private void vegimgup4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegimgup4ActionPerformed

        String path4 = null;
       
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        path4 = f.getAbsolutePath();
        pathimg4 = path4;
       // System.out.println(path4);
        try {
            BufferedImage bi = ImageIO.read(new File(path4));
            Image img = bi.getScaledInstance(134, 172, Image.SCALE_SMOOTH );
            ImageIcon icon = new ImageIcon(img);
            //farphoto.setIcon(icon);
            
        } catch (IOException ex) {
            //Logger.getLogger(FarmerReg.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        pb = new PBThread(vegprogressbar);
        pb.start();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_vegimgup4ActionPerformed

    private void veghindinameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veghindinameActionPerformed

        db3 = new ParabitDB();
        String hname = (String)veghindiname.getSelectedItem();
        String qimg = "SELECT Image FROM productlist WHERE HName = '"+hname+"'";
            
        try {
          
            db3.rs = db3.stm.executeQuery(qimg);
            db3.rs.next();
            BufferedImage bi = ImageIO.read(db3.rs.getBinaryStream("Image"));
            Image img = bi.getScaledInstance(150, 150, Image.SCALE_SMOOTH );
            vegimg.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            System.out.println(e);
        }
        
        //for vegetable name
        db3 = new ParabitDB();
        try
        {
            db3.rs = db3.stm.executeQuery("SELECT Name FROM productlist WHERE HName = '"+hname+"'");
            //db3.rs.next();
            while(db3.rs.next())
            {
                String vname = db3.rs.getString(1);
                vegname.setSelectedItem(vname);
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        //for vegetable regional name
       /* db1 = new ParabitDB();
        try
        {
            db1.rs = db1.stm.executeQuery("SELECT RName FROM productlist WHERE HName = '"+hname+"'");
           // db1.rs.next();
            while(db1.rs.next())
            {
                String rname = db3.rs.getString(1);
                vegregname.setSelectedItem(rname);
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        // To get value of id from database
        db2 = new ParabitDB();
        try
        {
            db2.rs = db2.stm.executeQuery("select SNo from productlist where WHERE HName = '"+hname+"'");
           
              db2.rs.next();
              id = db2.rs.getInt(1);
                  vegid.setText("Vegetable Id : "+id);
        }catch(Exception e)
        {
            System.out.println(e);
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_veghindinameActionPerformed

    private void vegnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegnameMouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_vegnameMouseEntered

    private void vegfaridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegfaridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vegfaridActionPerformed

    private void vegregnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegregnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vegregnameActionPerformed

    private void vegcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegcatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vegcatActionPerformed

    private void vegcolourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegcolourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vegcolourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VegetableReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VegetableReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VegetableReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VegetableReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                String b = null;
                VegetableReg dialog = new VegetableReg(new javax.swing.JFrame(), true,a,b);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField vegarea;
    private javax.swing.JComboBox<String> vegcat;
    private javax.swing.JComboBox<String> vegcolour;
    private javax.swing.JComboBox<String> vegcutdate;
    private com.toedter.calendar.JMonthChooser vegcutmonth;
    private com.toedter.calendar.JYearChooser vegcutyear;
    private javax.swing.JTextField vegfarid;
    private javax.swing.JComboBox<String> veghindiname;
    private javax.swing.JLabel vegid;
    private javax.swing.JLabel vegimg;
    private javax.swing.JButton vegimgup1;
    private javax.swing.JButton vegimgup2;
    private javax.swing.JButton vegimgup4;
    private javax.swing.JButton vegimpup3;
    private javax.swing.JRadioButton veginorganic;
    private javax.swing.JTextField veglccoord;
    private javax.swing.JComboBox<String> vegname;
    private javax.swing.JRadioButton vegorganic;
    private javax.swing.JProgressBar vegprogressbar;
    private javax.swing.JTextField vegqactual;
    private javax.swing.JTextField vegqexpected;
    private javax.swing.JTextField vegqplanted;
    private javax.swing.JComboBox<String> vegregname;
    private javax.swing.JButton vegsubreg;
    // End of variables declaration//GEN-END:variables
}
